README.md, cli.go, help.go
This description is not explicitly returning an error code...
=> Fix --error-with-issues description

detector/aws_instance_invalid_type.go
=> r4.xlarge is valid type

detector/aws_instance_invalid_type.go
=> Support I3 instance types

README.md
I submitted TFLint to Homebrew, but they said the project wasn't popular enough for them to accept; so I made a custom tap.
@wata727 I would be happy to make you a co-maintainer of the tap so that you could update it when you release a new TFLint version, or alternately just let me know and I'll update it.
=> Update README to reference Homebrew tap

README.md, detector/aws_instance_not_specified_iam_profile.go, detector/aws_instance_not_specified_iam_profile_test.go, docs/aws_instance_not_specified_iam_profile.md
Fix #53 
Terraform 0.8.8 and later can change IAM profile later 🎉
=> Add NOTE to aws_instance_not_specified_iam_profile

README.md
Homebrew package: https://github.com/wata727/homebrew-tflint
Great thanks to @hakamadare !
=> Transfer from hakamadare/tflint to wata727/tflint

detector/aws_route_specified_multiple_targets.go, detector/aws_route_specified_multiple_targets_test.go, detector/detector.go, docs/README.md, docs/aws_route_specified_multiple_targets.md
This detector detects multiple routing targets specified.
=> Add AwsRouteSpecifiedMultipleTargetsDetector

config/aws.go, detector/aws_route_invalid_gateway.go, detector/aws_route_invalid_gateway_test.go, detector/detector.go, docs/README.md
This detector detects invalid gateway id references.
=> Add AwsRouteInvalidGatewayDetector

config/aws.go, detector/aws_route_invalid_egress_only_gateway.go, detector/aws_route_invalid_egress_only_gateway_test.go, detector/detector.go, docs/README.md
This detector detects invalid egress only gateway references.
=> Add AwsRouteInvalidEgressOnlyGatewayDetector

config/aws.go, detector/aws_route_invalid_nat_gateway.go, detector/aws_route_invalid_nat_gateway_test.go, detector/detector.go, docs/README.md
This detector detects invalid NAT gateway references.
=> Add AwsRouteInvalidNatGatewayDetector

config/aws.go, detector/aws_route_invalid_network_interface.go, detector/aws_route_invalid_network_interface_test.go, detector/detector.go, docs/README.md
This detector detects invalid network interface references.
=> Add AwsRouteInvalidNetworkInterfaceDetector

integration/general/.terraform/modules/0cf2d4dab02de8de33c7058799b6f81e/aws_db_instance.tf, integration/general/.terraform/modules/0cf2d4dab02de8de33c7058799b6f81e/aws_elasticache_cluster.tf, integration/general/.terraform/modules/0cf2d4dab02de8de33c7058799b6f81e/aws_instance.tf, integration/general/result.json, integration/general/template.tf, integration/general/terraform.tfvars, integration_test.go, issue/issue.go
=> Add integration test

evaluator/module.go
=> DO NOT USE Evaluator :bow:

README.md, config/config.go, config/config_test.go, config/test-fixtures/.tflint.hcl
=> Add Terraform version options

config/config.go, config/config_test.go, main.go
=> Handle empty config file

main.go
=> Handle color for Windows

README.md
Follow up of https://github.com/wata727/tflint/issues/195
=> Add note for installation

README.md
=> Recommend `rule` syntax instead of `ignore_rules` in README

README.md
Follow up of https://github.com/wata727/tflint/issues/212
=> Add `rule` section in README

detector/aws_db_instance_invalid_type.go
See:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html
=> Add missing db instances as valid types

Gopkg.lock
Fixes #225 
In addition, also want to add support for the t3 family so I'm waiting for merging the following pull request:
https://github.com/cristim/ec2-instances-info/pull/5
=> Update valid instance list

client/aws.go, cmd/cli.go, cmd/cli_test.go, rules/awsrules/aws_instance_invalid_ami.go, rules/awsrules/aws_instance_invalid_type.go, rules/provider.go, tflint/config.go, tflint/config_test.go, tflint/loader.go, tflint/loader_test.go, tflint/runner.go, tflint/runner_test.go, tflint/terraform.go
For user experience, I review all error messages and log level and output.
=> Tweak error message and logs

Dockerfile, Makefile
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
=> Rewrite Dockerfile multi-stage

rules/awsrules/aws_instance_default_standard_volume_test.go, tflint/runner.go, tflint/runner_test.go
Maps and lists that contain null or unknown values are also marked as null or unknown as well.
=> Also ignore expressions including unknown/null values

.pre-commit-config.yaml, .pre-commit-hooks.yaml, docs/DEVELOPING.md
For now added only gofmt, which is required. Worth to check other
possibilities under: https://github.com/dnephin/pre-commit-golang
Put into Developing documentation also info about it.
=> Added pre-commit hooks

azure-pipelines.yml, tflint/annotation_test.go, tflint/loader_test.go, tflint/runner_test.go, tflint/tflint_test.go
Currently, Windows build looks unstable. I'm not sure if this is an issue with AppVeyor, but to identify the cause, I will test Windows CI with Azure Pipelines.
=> Set up CI with Azure Pipelines

docs/rules/README.md, docs/rules/terraform_dash_in_resource_name.md, rules/provider.go, rules/terraformrules/terraform_dash_in_resource_name.go, rules/terraformrules/terraform_dash_in_resource_name_test.go
An attempt to begin working on #273. Wanted to start with a small patch so I could get any needed feed back before making any more.
=> Add terraform_dash_in_resource_name rule

README.md
Make it clear to doesn't work with Terraform v0.11.x
=> Add Terraform compatibility badge

.github/workflows/release.yml, .goreleaser.yml
We can build a fully documented release workflow by automating releases with GitHub Actions 🦄 
For that, release as a draft with GoReleaser so that sign the checksums manually.
=> Release via GitHub Actions

.goreleaser.yml
See https://github.com/wata727/tflint/runs/202166322
Generated code is already committed.
=> Remove GoReleaser before hooks

Makefile, docs/DEVELOPING.md
`make tools` install the required tools for building.
=> Add tools task to Makefile and clean up

README.md
I completely misunderstood about iota 😭
=> docs: Fix exit status

azure-pipelines.yml
=> Upgrade Go version to 1.13 on Azure Pipelines

.github/workflows/release.yml, .travis.yml, Dockerfile, docs/DEVELOPING.md, go.mod, tools/go.mod
Good to keep it with the latest golang version. :)
=> Upgrade to go 1.13

docs/guides/README.md, docs/guides/annotations.md, docs/guides/config.md
Move documentation about annotation comments to the top level.
=> docs: Add annotations page

cmd/cli.go, cmd/cli_test.go, rules/awsrules/aws_db_instance_default_parameter_group.go, rules/awsrules/aws_db_instance_invalid_type.go, rules/awsrules/aws_db_instance_previous_type.go, rules/awsrules/aws_elasticache_cluster_default_parameter_group.go, rules/awsrules/aws_elasticache_cluster_invalid_type.go, rules/awsrules/aws_elasticache_cluster_previous_type.go, rules/awsrules/aws_instance_previous_type.go, rules/awsrules/aws_route_not_specified_target.go, rules/awsrules/aws_route_specified_multiple_targets.go, rules/terraformrules/terraform_dash_in_resource_name.go, rules/terraformrules/terraform_documented_outputs.go, rules/terraformrules/terraform_documented_variables.go, rules/terraformrules/terraform_module_pinned_source.go, tflint/meta.go
=> Remove project package

docs/guides/compatibility.md, go.mod, go.sum, tools/go.mod, tools/go.sum
See https://github.com/hashicorp/terraform/releases/tag/v0.12.10
=> Bump terraform from 0.12.9 to 0.12.10

.github/workflows/generated_code_checks.yml, .github/workflows/release.yml, tflint/loader.go
=> Test tools in GitHub Actions

docs/rules/README.md, docs/rules/terraform_module_semver_source.md, rules/provider.go, rules/terraformrules/terraform_module_pinned_source.go, rules/terraformrules/terraform_module_semver_source.go, rules/terraformrules/terraform_module_semver_source_test.go
Closes #513.
Thanks for providing good developer documentation. Made it really easy to write this patch! 😄
=> Add an optional checker for semver versions

docs/guides/compatibility.md, go.mod, go.sum, integration/plugin/go.sum, plugin/test-fixtures/plugins/go.sum
https://github.com/hashicorp/terraform/releases/tag/v0.12.14
https://github.com/hashicorp/terraform/releases/tag/v0.12.15
=> Bump terraform to v0.12.15 from v0.12.13

.github/ISSUE_TEMPLATE/bug_report.md, docs/guides/compatibility.md, go.mod, go.sum
Bump the version to latest, v0.12.16
=> terraform 0.12.16

.github/workflows/build.yml, .github/workflows/generated_code_checks.yml, .github/workflows/release.yml
See https://github.com/actions/checkout/issues/81#issuecomment-561252016
=> Pin actions/checkout@v1

.github/workflows/docker.yml
=> Add docker build actions

.github/workflows/build.yml, .github/workflows/generated_code_checks.yml, .github/workflows/release.yml, Dockerfile, docs/DEVELOPING.md, go.mod, tools/go.mod
homebrew formula has been cross verified in this PR, Homebrew/homebrew-core#50687
=> Bump golang to v1.14

.github/workflows/homebrew.yml
Fixes #683
relates to https://github.com/Homebrew/homebrew-core/pull/52008
=> Automate homebrew formula upgrade process

docs/rules/aws_db_instance_previous_type.md, docs/rules/aws_instance_previous_type.md, docs/rules/aws_route_not_specified_target.md, docs/rules/aws_route_specified_multiple_targets.md, docs/rules/terraform_deprecated_interpolation.md, docs/rules/terraform_module_pinned_source.md
This PR makes assorted grammar edits to the rules docs that I noticed as I was reading them and enabling rules.
Thank you for all your work here, excited to see the project moving in a modular direction!
=> Copy edits for rules docs

plugin/discovery.go
Windows does not _require_ the `.exe` extension and this was causing some confusing when trying to create the `tflint` binary using `-o` with go build.
=> Allow no extensions on windows

go.mod, go.sum, plugin/server.go
See https://github.com/terraform-linters/tflint-plugin-sdk/pull/35
=> plugin: Allow to omit metadata expr on EmitIssue

go.mod, go.sum, plugin/encode.go, plugin/server.go, plugin/server_test.go, tflint/terraform.go, tflint/terraform_test.go
See https://github.com/terraform-linters/tflint/issues/669
See https://github.com/terraform-linters/tflint-plugin-sdk/pull/37
This PR extends the API so that the host process can return the advanced resources merged into tflint-plugin-sdk.
=> plugin: Support meta-arguments for Resource

README.md, cmd/cli.go, cmd/option.go, main.go
=> Add `--loglevel` option

go.mod, go.sum, plugin/encode.go, plugin/server_test.go
This change corresponds to https://github.com/terraform-linters/tflint-plugin-sdk/pull/59
=> plugin: Add `Provider` field to `terraform.Resource`

go.mod, go.sum, plugin/encode.go, plugin/server.go, plugin/server_test.go
This change corresponds to https://github.com/terraform-linters/tflint-plugin-sdk/pull/60
=> plugin: Add `Config()` method to the plugin server

go.mod, go.sum, rules/awsrules/models/aws_alb_invalid_load_balancer_type.go, rules/awsrules/models/aws_alb_listener_invalid_protocol.go, rules/awsrules/models/aws_alb_target_group_invalid_protocol.go, rules/awsrules/models/aws_appautoscaling_policy_invalid_scalable_dimension.go, rules/awsrules/models/aws_appautoscaling_policy_invalid_service_namespace.go, rules/awsrules/models/aws_appautoscaling_scheduled_action_invalid_scalable_dimension.go, rules/awsrules/models/aws_appautoscaling_scheduled_action_invalid_service_namespace.go, rules/awsrules/models/aws_appautoscaling_target_invalid_scalable_dimension.go, rules/awsrules/models/aws_appautoscaling_target_invalid_service_namespace.go, rules/awsrules/models/aws_datasync_location_s3_invalid_s3_bucket_arn.go, rules/awsrules/models/aws_datasync_location_s3_invalid_s3_bucket_arn_test.go, rules/awsrules/models/aws_directory_service_directory_invalid_short_name.go, rules/awsrules/models/aws_directory_service_directory_invalid_short_name_test.go, rules/awsrules/models/aws_instance_invalid_type.go, rules/awsrules/models/aws_launch_configuration_invalid_type.go, rules/awsrules/models/aws_launch_template_invalid_instance_type.go, rules/awsrules/models/aws_lb_invalid_load_balancer_type.go, rules/awsrules/models/aws_lb_listener_invalid_protocol.go, rules/awsrules/models/aws_lb_target_group_invalid_protocol.go, rules/awsrules/models/aws_mq_broker_invalid_deployment_mode.go, rules/awsrules/models/aws_s3_bucket_object_invalid_storage_class.go, rules/awsrules/models/aws_vpc_endpoint_invalid_vpc_endpoint_type.go
=> update aws-sdk, generate rules

docs/rules/aws_route_not_specified_target.md, integration/basic/result.json, rules/awsrules/aws_route_not_specified_target.go, rules/awsrules/aws_route_not_specified_target_test.go
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/route#vpc_endpoint_id
=> [aws_route_not_specified_target] Add "vpc_endpoint_id" Route Target

tflint/runner_walk.go, tflint/runner_walk_test.go
Closes https://github.com/terraform-linters/tflint/issues/1002
This issue was discovered during the investigation of https://github.com/terraform-linters/tflint/pull/1019. I could only avoid the error because there was no way to walk through the merged body...
=> tflint: Skip walking expressions of merged bodies

go.mod, go.sum, integrationtest/inspection/heredoc/.tflint.hcl, integrationtest/inspection/heredoc/result.json, integrationtest/inspection/heredoc/result_windows.json, integrationtest/inspection/heredoc/template.tf, integrationtest/inspection/inspection_test.go, tflint/terraform.go
Fixes https://github.com/terraform-linters/tflint/issues/1029
See https://github.com/terraform-linters/tflint-plugin-sdk/pull/93
See https://github.com/hashicorp/hcl/issues/441
=> Add workaround for parsing heredoc expressions

.github/workflows/e2e.yml, .github/workflows/generated_code_checks.yml
Brings the same changes in #1046 to the E2E and generated code workflows.
=> add module/build caching to e2e + gen

cmd/option.go, cmd/option_test.go, tflint/config.go
This adds a CLI option to enable plugins.
https://github.com/terraform-linters/tflint/pull/1039#issuecomment-764896952
=> Added option to enable plugins from the cli

README.md
add stargazers chart for fun :)
=> add stargazers chart

plugin/server.go
Fixes https://github.com/terraform-linters/tflint/issues/1078
If the `for_each` argument contains an undeclared variable, it occurs an application error. However, this is not a registered type on the plugin side, so will result in an error during gob encoding.
To prevent this, cast to an error with the equivalent format defined in tflint-plugin-sdk. In addition, the cause error may also contain an unencodable error, so regenerate the error as `tflint.Error`.
=> plugin: Wrap errors to avoid gob encoding errors

.github/dependabot.yml
=> update dependabot to manage docker deps

README.md
Add a link to [setup-tflint](https://github.com/terraform-linters/setup-tflint) action in README.
=> Add README about GitHub Actions

go.mod, go.sum, integrationtest/bundled/cty-based-eval/result.json, integrationtest/bundled/map-attribute/result.json, integrationtest/bundled/rule-config/result.json
https://github.com/terraform-linters/tflint-ruleset-aws/releases/tag/v0.4.0
=> Bump bundled AWS ruleset plugin

.github/workflows/install_script.yml, install_linux.sh
When running as root (UID=0), don't prefix commands with sudo
Closes #1101
=> install: handle running as root (without sudo)

docs/rules/terraform_required_version.md
=> Fix description for terraform_required_version

.github/workflows/docker.yml, README.md
Fixes https://github.com/terraform-linters/tflint/issues/1133
=> Migrate to GitHub Container Registry

go.mod, go.sum
https://github.com/sourcegraph/jsonrpc2/compare/35a74f039c6a...v0.1.0
=> Bump github.com/sourcegraph/jsonrpc2 to v0.1.0

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/generate.yml
=> build: get cache paths from go env

docs/rules/terraform_required_version.md
Change documentation to reflect required_version, not required_providers
=> fix incorrect documentation

.github/workflows/goreleaser.yml, .goreleaser.yml
Fixes https://github.com/terraform-linters/tflint/issues/1219
=> build: Remove some os/arch build targets

docs/rules/README.md
Some minor changes.
- Updated rules readme file with missing rule
- Put table in alphabetical order
=> add missing rule to index, alphabetize

Dockerfile
Follow up of https://github.com/terraform-linters/tflint/pull/1265
=> Bump alpine to 3.15 in builder layer

docs/user-guide/compatibility.md
Follow up of https://github.com/terraform-linters/tflint/pull/1276
=> Update Compatibility guide

go.mod, go.sum, plugin/server.go, plugin/server_test.go, tflint/runner.go, tflint/runner_eval_test.go, tflint/runner_test.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/148
This PR brings the optimizations adopted by the tflint-plugin-sdk to the server.
=> plugin: Optimize GetModuleContent API calls

go.mod, go.sum
See https://github.com/terraform-linters/tflint-plugin-sdk/releases/tag/v0.10.0
=> Bump tflint-plugin-sdk to v0.10.0

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/generate.yml, .github/workflows/goreleaser.yml, .github/workflows/lint.yml, .github/workflows/release.yml, docs/developer-guide/building.md, go.mod, go.sum
https://tip.golang.org/doc/go1.18
And, I will update the GoReleaser version to the latest.
=> build: Go 1.18

go.mod, go.sum
https://github.com/terraform-linters/tflint-plugin-sdk/releases/tag/v0.11.0
=> Bump tflint-plugin-sdk to v0.11.0

terraform/configs/resource.go
As #1388 said we need to support new feature in v1.2.0.
Hello @wata727 , this is the first time I submit pr to tflint repo, I'm not sure the whether this patch meets tflint's requirement, would you please give it a review since I have pending issue depends on `replace_triggered_by`? Thanks a lot!
=> Add support for `replace_triggered_by` in `lifecycle`

.github/workflows/release.yml
v0.38.0 release was failed with the following message:
```
Error: signing dist/checksums.txt: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input
main.go:46: error during command execution: signing dist/checksums.txt: getting key from Fulcio: verifying SCT: unmarshal: unexpected end of JSON input
```
https://github.com/terraform-linters/tflint/runs/6970856372?check_suite_focus=true
=> Use latest Cosign

.github/workflows/homebrew.yml
adopted [from the comment ](https://github.com/Homebrew/homebrew-core/pull/106670)
=> workflow(homebrew): update to use personal fork

tflint/runner.go
=> runner: fix typo

install_linux.sh
Prevent TOCTOU when intstalling.
=> use mktemp when installing tflint

terraform/module_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1547
This bug has been fixed in https://github.com/terraform-linters/tflint/pull/1537. This PR adds a test to make sure it's fixed.
=> Add test when the count is string

README.md, go.mod, go.sum
https://github.com/terraform-linters/tflint-ruleset-terraform/releases/tag/v0.2.0
https://github.com/terraform-linters/tflint-plugin-sdk/releases/tag/v0.14.0
=> Bump tflint-plugin-sdk and bundled terraform plugin

go.mod, go.sum
https://github.com/terraform-linters/tflint-ruleset-terraform/releases/tag/v0.2.1
=> Bump bundled terraform plugin to v0.2.1

terraform/LICENSE
Follow up of https://github.com/hashicorp/terraform/pull/32002
=> Follow up of upstream LICENSE updates

.github/workflows/install_script.yml
Follow up of https://github.com/terraform-linters/tflint/pull/1627
=> chores: Pass GITHUB_TOKEN to container install script

go.mod, go.sum
https://github.com/terraform-linters/tflint-ruleset-terraform/releases/tag/v0.2.2
=> Bump bundled terraform ruleset to v0.2.2

docs/developer-guide/architecture.md
inspection was written as inspecion on line 16 in read me
=> corrected inspection spelling on line 16

README.md
Fixes https://github.com/terraform-linters/tflint/issues/1358
[TFLint OPA ruleset](https://github.com/terraform-linters/tflint-ruleset-opa) has been released 🎉 
This PR adds a link to the ruleset and plugin developer guide.
=> Mention OPA ruleset

docs/user-guide/README.md, docs/user-guide/environment_variables.md
This PR adds "Environment Variables" documentation. This document describes the list of environment variables available in TFLint.
=> docs: Add Environment Variables documentation

terraform/evaluator.go
Follow up of https://github.com/hashicorp/terraform/pull/32454
=> terraform: Follow up on upstream changes regarding evaluation

.goreleaser.yml
See also https://github.com/terraform-linters/tflint-ruleset-aws/pull/465
=> Fix GoReleaser config for Cosign v2

cmd/langserver.go
Fixes https://github.com/terraform-linters/tflint/issues/1808
Since language server does not handle signals, there is a problem that plugin processes will not be terminated when the process is terminated due to an interrupt or SIGTERM.
```console
$ tflint --langserver
14:21:12 langserver.go:26: Starting language server...
^C
$ ps -efw | grep tflint
codespa+   13508       1  0 14:21 pts/0    00:00:00 /go/bin/tflint --act-as-bundled-plugin
codespa+   13549     528  0 14:21 pts/0    00:00:00 grep --color=auto tflint
```
This PR changes the language server to exit gracefully if `os.Interrupt` or `syscall.SIGTERM` is sent.
```console
$ tflint --langserver
14:54:48 langserver.go:28: Starting language server...
^C14:54:50 langserver.go:50: Received interrupt, shutting down...
$ ps -efw | grep …
```
=> langserver: Trap os.Interrupt and syscall.SIGTERM

go.mod
See https://go.dev/doc/devel/release#go1.22.minor
=> deps: Go 1.22.4

.github/workflows/lint.yml, Dockerfile, cmd/inspect_parallel.go, docs/developer-guide/building.md, formatter/formatter_test.go, go.mod, plugin/server_test.go, terraform/lang/function_calls_test.go, terraform/parser_test.go, tflint/annotation_test.go, tflint/runner_test.go
- https://go.dev/doc/devel/release#go1.23.0
=> chore: bump to use go 1.23.0

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/e2e.yml, .github/workflows/generate.yml, .github/workflows/goreleaser.yml, .github/workflows/homebrew.yml, .github/workflows/install_script.yml, .github/workflows/lint.yml, .github/workflows/release.yml
- run with `frizbee actions .github/workflows/` (https://github.com/stacklok/frizbee)
=> chore: pin workflow action sha

Dockerfile
See https://docs.docker.com/reference/build-checks/from-as-casing/
=> Fix FromAsCasting build check failure

.github/workflows/lint.yml, Dockerfile
=> build(deps): Bump alpine to 3.21 and golangci-lint to 1.62.2

plugin/install.go
Extract the plugin verifications into functions.
=> Refactor plugin verifications

docs/user-guide/compatibility.md, go.mod, terraform/lang/funcs/collection.go, terraform/lang/funcs/collection_test.go, terraform/lang/funcs/string.go, terraform/lang/funcs/string_test.go
Fixes https://github.com/terraform-linters/tflint/issues/2257
This PR adds support for the following features added in Terraform v1.11:
- https://github.com/hashicorp/terraform/pull/36611
- https://github.com/hashicorp/terraform/pull/36658
=> Add support for Terraform v1.11

.github/workflows/build.yml, .github/workflows/docker.yml, .github/workflows/e2e.yml, .github/workflows/generate.yml, .github/workflows/goreleaser.yml, .github/workflows/homebrew.yml, .github/workflows/install_script.yml, .github/workflows/lint.yml
Fix actions/missing-workflow-permissions in Code Scanning alerts
=> Set explicit workflow permissions

.github/workflows/goreleaser.yml, .github/workflows/release.yml, .goreleaser.yml
See also https://goreleaser.com/deprecations/#archivesformat
=> Bump GoReleaser to v2.11.0

.github/workflows/lint.yml, go.mod
https://tip.golang.org/doc/go1.25
=> deps: Bump Go version to 1.25
