terraform-linters/tflint

- README.md
I found zero width spaces in README.md .
It seems unnecessary. So, I removed it.
Unicode document: http://www.fileformat.info/info/unicode/char/200B/index.htm
GitHub UI maybe can't display the difference.
You can see it by `git diff` command in terminal.
> Remove Zero width space in README.md

- detector/detector.go
The following panic occurred in deep detecting with module.
```
$ tflint --deep -c .tflint.hcl.config --debug
DEBUG:/loader.go:84 [INFO] load `.tflint.hcl.config`
DEBUG:/loader.go:84 [INFO] load `module.tf`
DEBUG:/loader.go:38 [INFO] load module `./tf_aws_ec2_instance`
DEBUG:/loader.go:84 [INFO] load `.terraform/modules/960d94c2f60d34845dc3051edfad76e1/main.tf`
DEBUG:/loader.go:84 [INFO] load `.terraform/modules/960d94c2f60d34845dc3051edfad76e1/outputs.tf`
DEBUG:/loader.go:84 [INFO] load `.terraform/modules/960d94c2f60d34845dc3051edfad76e1/variables.tf`
DEBUG:/aws.go:30 [INFO] set AWS region
DEBUG:/detector.go:84 [INFO] detect by `aws_instance_default_standard_volume`
DEBUG:/detector.go:93 [INFO] detect module `960d94c2f60d34845dc3051edfad76e1`
DEBUG:/detector.go:84 [INFO] detect by …
```
> Fix panic deep detecting with module

- detector/aws_db_instance_default_parameter_group.go
- detector/aws_db_instance_default_parameter_group_test.go
- detector/aws_elasticache_cluster_default_parameter_group.go
- detector/aws_elasticache_cluster_default_parameter_group_test.go
- detector/aws_instance_default_standard_volume.go
- detector/aws_instance_default_standard_volume_test.go
- detector/aws_instance_invalid_ami.go
- detector/aws_instance_invalid_ami_test.go
- detector/aws_instance_invalid_iam_profile.go
- detector/aws_instance_invalid_iam_profile_test.go
- detector/aws_instance_invalid_type.go
- detector/aws_instance_invalid_type_test.go
- detector/aws_instance_not_specified_iam_profile.go
- detector/aws_instance_not_specified_iam_profile_test.go
- detector/aws_instance_previous_type.go
- detector/aws_instance_previous_type_test.go
- detector/detector.go
- detector/detector_test.go
- detector/response_cache.go
- detector/test_helper.go
Fix #9 
Add cache mechanism for core detector. The following is an example of a deep check detecting that contains single module.
```
tflint -c .tflint.hcl.config  29.35s user 1.08s system 79% cpu 38.119 total
```
```
tflint -c .tflint.hcl.config  13.53s user 0.47s system 77% cpu 18.154 total
```
> Improve ineffecient module detector method

- detector/aws_instance_invalid_ami.go
- detector/aws_instance_invalid_iam_profile.go
- detector/aws_instance_invalid_key_name.go
- detector/aws_instance_invalid_subnet.go
- detector/aws_instance_invalid_vpc_security_group.go
- detector/detector.go
- detector/detector_test.go
Fix #14 
Following example is detecting simple template (only "provider")
```
tflint --deep --aws-region us-east-1  22.29s user 1.30s system 47% cpu 49.193 total
```
```
tflint --deep --aws-region us-east-1  0.00s user 0.01s system 79% cpu 0.015 total
```
> do not call API when target resources are not found

- detector/aws_elb_invalid_instance.go
- detector/aws_elb_invalid_security_group.go
- detector/aws_elb_invalid_subnet.go
- detector/aws_instance_invalid_vpc_security_group.go
- detector/detector.go
- detector/detector_test.go
- detector/test_helper.go
This PR made support list type variables evaluation. Previously, false negatives occurred in the following cases:
```
variable "security_groups" {
type = "list"
default = [
"sg-12345678", # This security group does not found
"sg-1234abcd",
]
}
resource "aws_instance" {
vpc_security_group_ids = "${var.security_groups}"
}
```
> support list type variables evaluation

- README.md
- cli.go
- help.go
When used tflint on CI, it's didn't failed although tflint return some errors.
Update to return 2 when issue exists.
> Return error code when issue exists

- cli.go
- cli_test.go
- config/config.go
- detector/detector.go
- loader/loader.go
- loader/loader_test.go
- loader/test-fixtures/local-state/terraform.tfstate
- loader/test-fixtures/remote-state/.terraform/terraform.tfstate
- mock/loadermock.go
- state/state.go
- state/state_test.go
Fix #44 
TFState has current infrastructure state information by Terraform. In order to detect more complicated issues, it is necessary.
There are two types of TFState, local state and remote state. local state is default state, it is stored under the current directory as `terraform.tfstate`. On the other hand remote state is backend state (e.g. S3, Atlas, Consul, etc.), cache state is stored in `.terraform/terraform.tfstate`.
TFLint loads these state files. If there are not found, it will continue processing without error.
> Interpret TFState

- cli.go
- cli_test.go
- help.go
Currently, running TFLint enabled deep check mode is very slowly. This is because `aws_instance_invalid_ami` rule gets all the AMIs.
The `--fast` option ignores slow rule. By this option, we can specify deprecated rules if you want to do so quickly.
> Add --fast option

- evaluator/variable.go
- evaluator/variable_test.go
Fix #77 
If the variable is empty list, `reflect.Value` length is zero. Because in that case returns empty list of `hilast.Variable`.
When using empty map, it parses as empty list. However, there is no problem because empty map is never used in Terraform.
> Fix panic when parsing empty list

- README.md
- cli.go
- cli_test.go
- config/aws.go
- config/aws_test.go
- config/config.go
- config/config_test.go
- glide.lock
- glide.yaml
- help.go
- mock/ec2mock.go
- mock/elasticachemock.go
- mock/elbmock.go
- mock/elbv2mock.go
- mock/iammock.go
- mock/rdsmock.go
Fix #70 
We specify shared credentials by `--aws-profile` options or `profile` attributes. This credentials used in deep check mode.
> Support shared credentials

- README.md
- cli.go
- cli_test.go
- help.go
- printer/checkstyle.go
- printer/checkstyle_test.go
- printer/printer.go
- printer/printer_test.go
Fix #76 
Introduce new output format called [checkstyle](http://checkstyle.sourceforge.net/).
The output of this format can be parsed with Jenkins plugin.
> Add checkstyle format

- config/aws.go
- detector/aws_security_group_duplicate_name.go
- detector/aws_security_group_duplicate_name_test.go
Fix #88 
When security groups are on EC2-Classic, VPC ID is nil.
ref: https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#SecurityGroup
So, use DescribeAccountAttirbutes API instead of DescribeVpcs API to detect the default VPC. This response is `none` when support EC2-Classic platform.
> Fix panic when security groups are on EC2-Classic

- config/aws.go
- detector/aws_route_invalid_route_table.go
- detector/aws_route_invalid_route_table_test.go
- detector/detector.go
- docs/README.md
Fix #87 
This detector detects invalid route table ID references. For example:
```
resource "aws_route" "foo" {
route_table_id = "rtb-nat-gw-a" # invalid route table ID
}
```
Terraform result: 
```
Error applying plan:
1 error(s) occurred:
* aws_route.r: 1 error(s) occurred:
* aws_route.r: Error creating route: InvalidRouteTableId.Malformed: Invalid id: "rtb-nat-gw-a"
status code: 400, request id: hogehoge
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
TFLint result:
```
template.tf
ERROR:2 "rtb-nat-gw-a" is invalid route table ID.
Result: 1 issues  (1 errors , 0 …
```
> Add AwsRouteInvalidRouteTableDetector

- detector/aws_route_not_specified_target.go
- detector/aws_route_not_specified_target_test.go
- detector/detector.go
- docs/README.md
- docs/aws_route_not_specified_target.md
This detector detects an invalid routing target specified.
> Add AwsRouteNotSpecifiedTargetDetector

- config/aws.go
- detector/aws_route_invalid_vpc_peering_connection.go
- detector/aws_route_invalid_vpc_peering_connection_test.go
- detector/detector.go
- docs/README.md
This detector detects invalid VPC peering connection references.
> Add AwsRouteInvalidVpcPeeringConnectionDetector

- detector/aws_route_invalid_instance.go
- detector/aws_route_invalid_instance_test.go
- detector/aws_route_invalid_vpc_peering_connection.go
- detector/detector.go
- docs/README.md
This detector detects invalid instance references.
> Add AwsRouteInvalidInstanceDetector

- evaluator/evaluator.go
- evaluator/module.go
- evaluator/module_test.go
- evaluator/variable.go
Fix #104 
Until now, value of modules directly converts to Go variables after decode, So HIL variables was not supported in module attributes.
This PR changes the behavior to interpolate HIL variables.
> Interpolate module attributes

- detector/aws_instance_invalid_type.go
ref: https://aws.amazon.com/blogs/aws/ec2-f1-instances-with-fpgas-now-generally-available/
> Support F1 instances

- detector/aws_cloudwatch_metric_alarm_invalid_unit.go
- detector/aws_cloudwatch_metric_alarm_invalid_unit_test.go
- detector/detector.go
- docs/README.md
- docs/aws_cloudwatch_metric_alarm_invalid_unit.md
- integration/general/.terraform/modules/0cf2d4dab02de8de33c7058799b6f81e/aws_db_instance.tf
- integration/general/result.json
- integration/general/template.tf
Fix #101 
Please check the documentation for detector details.
> Add AwsCloudWatchMetricAlarmInvalidUnitDetector

- schema/schema.go
Fix this test: https://travis-ci.org/wata727/tflint/jobs/244248101
Override files are loaded last in alphabetical order. But, it was not working correctly.
> Fix override logic

- README.md
- detector/aws_instance_not_specified_iam_profile.go
- detector/aws_instance_not_specified_iam_profile_test.go
- docs/aws_instance_not_specified_iam_profile.md
- glide.lock
- glide.yaml
- integration/general/result.json
The target of `aws_instance_not_specified_iam_profile` detector is when using Terraform less than 0.8.8. ref: https://github.com/wata727/tflint/pull/81
By using the newly introduced `terraform_version`, TFLint will not report this issue unless conditions are satisfied. If it is not set, It is reported as before.
> Report `aws_instance_not_specified_iam_profile` only when `terraform_version` is less than 0.8.8

- evaluator/evaluator_test.go
- evaluator/variable.go
- evaluator/variable_test.go
Fix #129 
NOTE: I feel a sense of incompatibility to forcibly convert an integer value to a string value. However, Terraform does not have an attribute that must be an integer type.
> Fix panic for integer variables interpolation

- evaluator/module.go
Fixes #136 
```
$ tflint
1:3: unknown variable accessed: var.instance_typ
```
```
$ tflint
Evaluation error: 1:3: unknown variable accessed: var.instance_typ in template_override.tf:9
```
> Fix unclear error messages

- schema/module.go
- schema/module_test.go
- schema/test-fixtures/.terraform/modules/a4fbc206f00a6da596866799d651304c/test.tf
Fixes #143 
Since the digest has changed in Terraform v0.10.6, try to check the new digest module path.
See: https://github.com/hashicorp/terraform/commit/74955ffd4ab31c0f6db5719122128d0025b33976
> Support new digest module path

- schema/module.go
- schema/module_test.go
- schema/test-fixtures/.terraform/modules/a05af696a3cd2d41568711d03a18a026/test.tf
Fixes #148 
Module directory path seems to be changed in the new Terraform version again.
See: https://github.com/hashicorp/terraform/commit/1b01f1892091bdbd3c8e188bf3c3dcf5c9dc22ec
> Support moudle path for v0.10.7

- evaluator/variable.go
- evaluator/variable_test.go
Fixes #141 
See: https://www.terraform.io/docs/configuration/variables.html#environment-variables
> Support variables from environment variables

- Dockerfile
As per https://github.com/wata727/tflint/issues/154
> Add ca-certificates to Docker image for TLS requests to AWS

- .travis.yml
- evaluator/module.go
- evaluator/module_test.go
Fixes https://github.com/wata727/tflint/issues/157
If there is access to a map element using a key as module attributes, an evaluation error occurred. 
The string obtained from the token contains unnecessary double quotes. Therefore, it deletes this, but until now it deletes even the necessary double quotes.
```
"\"${var.ami_info}\"" => "${var.ami_info}"
```
```
"\"${var.amis[\"test1\"]}\" => "${var.amis[test1]}" # Oops!
```
Remove all leading and trailing double quotes. In other words, use `strings.Trim` instead of `strings.Replace`.
> Use `strings.Trim` instead of `strings.Replace`

- evaluator/evaluator.go
Ref: https://github.com/wata727/tflint/pull/161
There was no way to solve it when module detection failed due to TFLint problem. This p-r also applies `ignore_module` to module initialization.
```
$ tflint --ignore-module=hashicorp/consule/aws
ERROR: module `hashicorp/consul/aws` not found. Did you run `terraform get`?
```
```
$ tflint --ignore-module=hashicorp/consule/aws
Awesome! Your code is following the best practices :)
```
> Ignore module initialization when settings `ignore_module`

- appveyor.yml
- cli_test.go
- loader/loader.go
- main.go
- schema/module.go
> AppVeyor :rocket:

- cli.go
- cli_test.go
- loader/loader.go
- loader/loader_test.go
Fixes #169 
These changes allow using glob pattern and multiple files as arguments. For example:
```
$ tflint dev/*.tf
```
```
$ tflint dev/template.tf dev/variable.tf
```
> Accept glob and multiple input

- README.md
- cli.go
- config/config.go
- config/config_test.go
Fixes #173 
After these changes, TFLint loads `.tflint.hcl` under the home directory when a configuration file is missing.
> Fallback to config under the home directory

- detector/terraform_module_pinned_source.go
- detector/terraform_module_pinned_source_test.go
Resolves #193 
- Substitutes `strings.Contains` for `regexp.MatchString`
- Uses `regexp.MustCompile` as regexp is checked during tests
- Adds tests for generic git repositories with HTTPS and SSH formats
> Detect pinned sources using regular expressions

- evaluator/evaluator.go
- evaluator/evaluator_test.go
Fixes https://github.com/wata727/tflint/issues/170
Fixes https://github.com/wata727/tflint/issues/187
Modify the validation logic of expressions that TFLint can evaluate. Until now, it had been judge the expression is evaluable if contains `var` or `terraform` syntax. (Even if it contains an unevaluable function such as `replace`)
These changes makes it strictly perform this check to avoid errors. I considered incorporating [Terraform's build-in functions](https://github.com/hashicorp/terraform/blob/0cc9e050ecd4a46ba6448758c2edc0b29bef5695/config/interpolate_funcs.go#L62), but [the vendoring type problem](https://forum.golangbridge.org/t/version-mismatch-between-vendored-version-of-dependency-and-normal-version/4073) disturbs me... Built-in functions will become available after …
> Fix interpolation checking

- tflint/loader.go
- tflint/runner.go
- tflint/runner_test.go
- tflint/terraform.go
- tflint/tflint_test.go
As a part of refactoring, use standard logger instead of custom (existing) logger. Ultimately, existing loggers will be removed.
The caller's output can be substituted with `log.SetFlag(log.stdFlags | log.Longfile)`. Also, by introducing [`hashicorp/logutils`](https://github.com/hashicorp/logutils), we can control the log level. This package is used by callers of Runner and Loader (perhaps it will be the main package).
Along with that, the `--debug` option will be removed, and the user will specify the log level via environment variables and so on.
> Use standard logger instead of custom logger

- client/aws.go
- client/aws_test.go
- client/client_test.go
- rules/awsrules/aws_instance_invalid_ami.go
- rules/awsrules/aws_instance_invalid_ami_test.go
- rules/awsrules/aws_instance_invalid_type.go
- rules/awsrules/aws_instance_invalid_type_test.go
- rules/awsrules/awsrules_test.go
- rules/provider.go
- rules/provider_test.go
- tflint/errors.go
- tflint/runner.go
- tflint/runner_test.go
- tflint/test-fixtures/invalid_module_attribute/.terraform/modules/07be448a6067a2bba065bff4beea229d/resource.tf
- tflint/test-fixtures/invalid_module_attribute/.terraform/modules/modules.json
- tflint/test-fixtures/invalid_module_attribute/module.tf
- tflint/test-fixtures/invalid_module_attribute/module/resource.tf
- tflint/test-fixtures/nested_modules/.terraform/modules/07be448a6067a2bba065bff4beea229d/module.tf
- tflint/test-fixtures/nested_modules/.terraform/modules/07be448a6067a2bba065bff4beea229d/module1/resource.tf
- tflint/test-fixtures/nested_modules/.terraform/modules/a8d8930bc3c2ae53bf6e3bbcb3083d7b/resource.tf
- tflint/test-fixtures/nested_modules/.terraform/modules/modules.json
- tflint/test-fixtures/nested_modules/module.tf
- tflint/test-fixtures/nested_modules/module/module.tf
- tflint/test-fixtures/nested_modules/module/module1/resource.tf
- tflint/test-fixtures/no_modules/resource.tf
- tflint/test-fixtures/not_allowed_module_attribute/.terraform/modules/07be448a6067a2bba065bff4beea229d/resource.tf
- tflint/test-fixtures/not_allowed_module_attribute/.terraform/modules/modules.json
- tflint/test-fixtures/not_allowed_module_attribute/module.tf
- tflint/test-fixtures/not_allowed_module_attribute/module/resource.tf
This PR introduces new helpers named `NewModuleRunners`. This function recursively searches for the children of `configs.Config` and returns runners as many as `configs.Config`.
Within the generated runner, assign the attributes of the module call as variables so that resources inside the module can be searched.
Variable that cannot be evaluated continues processing as an unknown value. This makes it unnecessary to assign dummy values when inspecting published modules and others.
Also, it introduces`rules.NewRules()` function. This function returns the rules for inspection based on the configuration.
> Handle resources and modules with Terraform's configs package

- tflint/runner.go
Remove the rules that find duplicate resources from the next minor release. The following rules will be unavailable.
- aws_security_group_duplicate_name
- aws_alb_duplicate_name
- aws_elb_duplicate_name
- aws_db_instance_duplicate_identifier
- aws_elasticache_cluster_duplicate_id
- aws_ecs_cluster_duplicate_name
In this PR, Terraform's state is removed from `Runner`. As a result, TFLint doesn't use Terraform's state.
The big motivation for this is change of tfstate format in Terraform 0.12. It is accompanied by technical difficulties of simultaneously supporting the previous state and new format.
The other is for the user experience. Although this feature is always assumed to be used after the `terraform plan`, many users expect to use in CI or to use with editors. This is a mismatch and …
> Remove duplicate resource rules

- cmd/cli.go
- cmd/cli_test.go
- mock/loader.go
- tflint/loader.go
- tflint/loader_test.go
- tflint/terraform.go
- tflint/test-fixtures/invalid_values_files/terraform.tfvars
- tflint/test-fixtures/values_files/auto1.auto.tfvars
- tflint/test-fixtures/values_files/auto2.auto.tfvars
- tflint/test-fixtures/values_files/cli1.tfvars
- tflint/test-fixtures/values_files/cli2.tfvars
- tflint/test-fixtures/values_files/terraform.tfvars
In this pull request, implements `LoadValuesFiles` API to load Terraform's values files.
This API detects automatically loaded values files such as `terraform.tfvars` and` * .auto.tfvars` and returns `terraform.InputValues` in order of priority. Support for `* .auto.tfvars` is a new feature.
The obtained input values are used to overwrite variables when passing it to `NewRunner`.
> Load Terraform's values files in Loader

- cmd/cli.go
- cmd/cli_test.go
- cmd/test-fixtures/arguments/README
- cmd/test-fixtures/arguments/template.tf
- cmd/test-fixtures/arguments/test.tf
- mock/loader.go
- tflint/loader.go
- tflint/loader_test.go
- tflint/runner.go
- tflint/runner_test.go
- tflint/test-fixtures/is_config_file/README
- tflint/test-fixtures/is_config_file/template.tf
Previously, file arguments were removed in #217, but I thought that similar feature is necessary for backward compatibility.
In the new TFLint, the file argument does not select the file to parse, it is used to filter issues. Therefore, parse all files regardless of arguments. This is a breaking change.
As a known issue, If file arguments are specified, module's issues are not reported. This will be improved by changing handling of module's issues in the future.
> Accept files arguments

- rules/awsrules/aws_instance_invalid_ami.go
- rules/awsrules/aws_instance_invalid_type.go
- rules/awsrules/aws_instance_invalid_type_test.go
- tflint/runner.go
- tflint/runner_test.go
This PR introduces `WalkResourceAttributes` and `EnsureNoError` helpers in Runner. These helpers will be used within `Check()` in rules package. The following is an example:
```go
runner.WalkResourceAttributes("aws_instance", "instance_type", func(attribute *hcl.Attribute) error {
// Check the attribute...
var instanceType string
err := runner.EvaluateExpr(attribute.Expr, &instanceType)
runner.EnsureNoError(err, func() error {
// Emit issues...
})
})
```
`WalkResourceAttributes` searches all attributes of the resource in the configurations and calls the received walker function with `hcl.Attribute`. This allows the caller to focus only on the processing of the target attribute.
`EnsureNoError` ensures that the received function is called only when it is not an error. This makes it …
> Add `WalkResourceAttributes` and `EnsureNoError` helpers

- tflint/runner.go
- tflint/runner_test.go
When `ignore_module` is set, do not report issues for the specified module.
As a breaking change, loading modules is necessary always. As a result, users who had avoided errors with this option may be affected by this change.
> Apply `ignore_module` to NewModuleRunners

- Gopkg.lock
- Gopkg.toml
- Makefile
- rules/awsrules/aws_db_instance_readable_password.go
- rules/awsrules/aws_db_instance_readable_password_test.go
- rules/provider.go
- rules/rule.go.tmpl
- rules/rule_test.go.tmpl
- tools/rule_generator.go
From this PR I will gradually migrate detectors to rules. At first, implement `aws_db_instance_readable_password` rule.
In the new implementation, it is possible to acquire variable references, so more detailed inspection than before is possible.
In addition, I'm adding a rule generator. This will help you to create new rules.
> Migrate `aws_db_instance_readable_password` to rules

- rules/provider.go
- rules/terraformrules/terraform_module_pinned_source.go
- rules/terraformrules/terraform_module_pinned_source_test.go
- rules/terraformrules/terraformrules_test.go
This PR introduces `terraformrules` package and migrate `terraform_module_pinned_source` to `rules` from `detector`.
At first, I planned to develop an API for walking module attributes, but since the `source` has been treated as a special attribute in Terraform, it is implemented without new API.
There is no change in behavior due to this migration.
> Migrate `terraform_module_pinned_source` to rules

- README.md
Fixes #236.
Might not be how you'd want this fixed, but I looked through with only eyes for features, and this would have helped (at least since I also did `CTRL+F`).
> Add "features" word to docs for people explicitly looking

- rules/awsrules/aws_instance_default_standard_volume.go
- rules/awsrules/aws_instance_default_standard_volume_test.go
- rules/provider.go
- tflint/runner.go
- tflint/runner_test.go
Migrate `aws_instance_default_standard_volume` rule as the process of migrating to the `rules` package from `detectors`.
In this rule, it needs to be able to access a map of a device block, so it makes `EvaluateExpr` API to accept a map value.
NOTE: The `aws_instance` resource can accept multiple `ebs_block_device` block, but an error occurs with the current Terraform's API:
```
Error: Failed to load configurations: instance.tf:14,5-21: Attribute redefined; The argument "ebs_block_device" was already set at instance.tf:9,5-21. Each argument may be set only once.
```
Since this problem may be resolved by the stable release of Terraform, mark this test as TODO in this pull request.
> Migrate `aws_instance_default_standard_volume` to rules

- rules/awsrules/aws_instance_default_standard_volume.go
- rules/awsrules/aws_instance_default_standard_volume_test.go
- tflint/runner.go
- tflint/runner_test.go
See also https://github.com/hashicorp/terraform/issues/19156
In HCL2, blocks and attributes are clearly distinguished. Until now, both were checked in the same way, but in the new implementation, it has to check each of them.
In this PR, introduce `WalkResourceBlocks` function to the `tflint.Runner`. This makes it easier to check blocks.
> Walk block definitions in aws_instance_default_standard_volume

- Gopkg.lock
This pulls in the most recent version of https://github.com/cristim/ec2-instances-info in order to get new instances
```
a1.2xlarge
a1.4xlarge
a1.large
a1.medium
a1.xlarge
c5n.18xlarge
c5n.2xlarge
c5n.4xlarge
c5n.9xlarge
c5n.large
c5n.xlarge
f1.4xlarge
g3s.xlarge
m5a.12xlarge
m5a.24xlarge
m5a.2xlarge
m5a.4xlarge
m5a.large
m5a.xlarge
r5a.12xlarge
r5a.24xlarge
r5a.2xlarge
r5a.4xlarge
r5a.large
r5a.xlarge
u-12tb1.metal
u-6tb1.metal
u-9tb1.metal
```
> Update ec2-instances-info dependency

- README.md
- install_linux.sh
Hopefully, this will address issue#263
> automate the installation of tflint on linux

- detector/aws_route_not_specified_target.go
- detector/aws_route_not_specified_target_test.go
- docs/aws_route_not_specified_target.md
- integration/general/result.json
Add `transit_gateway_id` as a valid argument for `aws_route`. Also clean up the docs and clarify the messages.
> Update aws_route_not_specified_target to handle transit_gateway_id

- LICENSE
In the next release, TFLint will depend on the Terraform's core packages to optimize implementation about Terraform's features (such as configuration loading, variable merging, and so on). For that reason, it refers to many of Terraform's implementations about loading modules and using APIs.
Terraform is licensed under the MPL 2.0. In MPL 2.0, "Large Work" (which refers to this project) must be distributed under that license or "Secondary Licenses" (See section 3.3).
From the above, I'm planning to change the license of this project from MIT to MPL 2.0.
No. It will be distributed with the same license as Terraform, so there is no impact on users generally.
Yes. The codes written by contributors will now be licensed as the MPL 2.0, not the MIT license. I hope to obtain the consent of all …
> Change license: MIT -> MPL 2.0

- tflint/runner_test.go
As a final step towards the 0.8 release, I will add test cases for v0.12 syntaxes.
As far as I confirmed, we cannot handle [null values](https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements) and [dynamic nested blocks](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each) correctly. The former will be fixed before releasing v0.8 because it occurs an error. The latter will be fixed in later releases because it doesn't report errors or false positives. To fix the issue, we need to introduce a way to evaluating blocks in Runner.
> Add test cases for v0.12 syntaxes

- rules/awsrules/aws_db_instance_readable_password_test.go
- rules/awsrules/aws_instance_default_standard_volume_test.go
- rules/awsrules/aws_route_not_specified_target.go
- rules/awsrules/aws_route_not_specified_target_test.go
- rules/awsrules/aws_route_specified_multiple_targets.go
- rules/awsrules/aws_route_specified_multiple_targets_test.go
- tflint/errors.go
- tflint/runner.go
- tflint/runner_test.go
Terraform v0.12 introduces `null` value to mark the attribute value as unset. TFLint doesn't handle the null values correctly, so some rules need to be fixed.
> Make rules aware of null values

- CHANGELOG.md
- docs/rules/aws_route_specified_multiple_targets.md
- rules/awsrules/aws_route_specified_multiple_targets.go
Follow up of #276 
This PR focused on the `aws_route_specified_multiple_targets` rule
> Make transit_gateway_id as a valid target on the multiple targets rule

- rules/awsrules/aws_instance_default_standard_volume.go
- rules/awsrules/aws_instance_default_standard_volume_test.go
If `volume_type` is null, `aws_instance_default_standard_volume` rule emits an issue.
Note that the `*_block_device` **attribute** doesn't emit an issue. This is because there is no way to distinguish which value is null when evaluating the attribute as a map. In such cases, TFLint doesn't always emit an issue to avoid false positives.
> Emit issues when the volume type is null

- .dockerignore
- Dockerfile
- Makefile
`docker build` raises an error because the` tflint` directory has been added.
> Revise docker image

- .gitignore
- .goreleaser.yml
- Makefile
Fixes #252
Switch the release way from [Gox](https://github.com/mitchellh/gox) to [GoReleaser](https://github.com/goreleaser/goreleaser). This allows us to manage release settings in a YAML file and automate things like signing keys.
There is also room for publishing docker images and brew formula, but this is not done here. In addition, a release is done manually on my local machine. Automating releases using GitHub Actions or CIs is also possible, but due to various difficulties, this is not considered here.
> Release via GoReleaser

- tflint/runner.go
Fix #295 
When checking whether an expression is null, it evaluates the expression before making sure that that is evaluable. As a result, it may cause unexpected errors.
Unfortunately, I have not confirmed whether this actually causes panic, but I think that the behavior may change with or without tfstate.
> Fix panic when checking whether an expression is null

- rules/awsrules/aws_instance_default_standard_volume_test.go
- tflint/runner.go
- tflint/runner_test.go
Terraform 0.12 adds support for dynamic nested blocks. At present, the `WalkResourceBlocks` API only extracts the structure on HCL and walks on it, so it cannot support such dynamic blocks.
For complete support, we need to evaluate and expand the blocks like Terraform way. [`ExpandBlock`](https://github.com/hashicorp/terraform/blob/v0.12.0/lang/eval.go#L19-L35) and [`EvalBlock`](https://github.com/hashicorp/terraform/blob/v0.12.0/lang/eval.go#L37-L72) are likely to be helpful. However, when evaluating a block, we must consider the possibility that the block contains unevaluable values such as unknown or unsupported references. Unfortunately, in that case, we must ignore all that block.
In this PR, in order to avoid this problem, we walk the dynamic block partially as the HCL structure …
> Walk on dynamic blocks partially

- rules/awsrules/aws_instance_invalid_ami.go
- rules/awsrules/aws_instance_invalid_ami_test.go
Currently, `aws_instance_invalid_ami` rule fetches all images first. However, these are very large and take a lot of time to complete the request. We just had to provide the `--fast` option just to disable this rule.
In this pull request, instead of fetching all images first, it will request each time as needed, and cache the list of fetched AMIs. This can reduce the time spent on requests and significantly reduce memory usage.
The number of requests simply increases, but in many cases, it is faster than fetching all images. Here is an example of `time` output:
**Before**
```
tflint --deep  46.28s user 10.51s system 63% cpu 1:29.18 total
```
**After**
```
tflint --deep  0.55s user 0.10s system 8% cpu 7.817 total
```
NOTE: The `--fast` option will be no longer used, and will be removed in …
> Make aws_instance_invalid_ami rule faster

- rules/awsrules/aws_instance_invalid_ami.go
- rules/awsrules/aws_instance_invalid_ami_test.go
- rules/awsrules/aws_launch_configuration_invalid_image_id.go
- rules/awsrules/aws_launch_configuration_invalid_image_id_test.go
`DescribeImages` may return an error when passing an invalid AMI ID. In the case, TFLint aborts the current inspection with the following error message:
```
$ tflint --deep
Error: Failed to check `aws_instance_invalid_ami` rule: An error occurred while describing images; InvalidAMIID.NotFound: The image id '[ami-0abc1234]' does not exist
```
This pull request changes the error handling to avoid these [expected errors](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#api-error-codes-table-client). It will emit issues instead.
> Avoid InvalidAMIID errors

- rules/awsrules/aws_s3_bucket_invalid_acl.go
- rules/awsrules/aws_s3_bucket_invalid_acl_test.go
- rules/provider.go
Add a new rule to check if the `acl` value specified for an `aws_s3_bucket` matches one of the [canned ACL types](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl).
> Add new rule: aws_s3_bucket_invalid_acl

- README.md
- cmd/cli.go
- cmd/cli_test.go
- cmd/option.go
- cmd/option_test.go
See also https://github.com/wata727/tflint/pull/308
The `--fast` option was helpful because it disables slow rules automatically. The only slow rule was the `aws_instance_invalid_ami` rule, but this has been faster enough at v0.8.2.
At this time, this option is useless and will be removed.
> Remove `--fast` option

- README.md
- cmd/cli.go
- cmd/option.go
- cmd/option_test.go
- integration/without_module_init/module.tf
- integration/without_module_init/result.json
- integration/without_module_init/template.tf
- integration_test.go
- tflint/config.go
- tflint/config_test.go
- tflint/loader.go
- tflint/loader_test.go
- tflint/runner_test.go
- tflint/test-fixtures/config/config.hcl
- tflint/tflint_test.go
Fixes #198, #248 
Disable module inspection by default, as described in #248.
The change allows you to perform an inspection without required additional steps. As before, if you want to do module inspection, perform with the `--module` option:
```
$ tflint --module
```
You can also enable/disable the option from a configuration file as follows:
```hcl
config {
module = true
}
```
> Disable module inspection by default

- docs/rules/README.md
- docs/rules/terraform_documented_outputs.md
- docs/rules/terraform_documented_variables.md
- rules/provider.go
- rules/terraformrules/terraform_documented_outputs.go
- rules/terraformrules/terraform_documented_outputs_test.go
- rules/terraformrules/terraform_documented_variables.go
- rules/terraformrules/terraform_documented_variables_test.go
Fixes #174 
These rules are disabled by default, so you need to write `.tflint.hcl` like the following if you'd like to enable these:
```hcl
rule "terraform_documented_outputs" {
enabled = true
}
rule "terraform_documented_variables" {
enabled = true
}
```
> Add terraform_documented_variables/outputs rules

- docs/guides/compatibility.md
- go.mod
- go.sum
- rules/awsrules/models/aws_cloudwatch_metric_alarm_invalid_comparison_operator.go
- tools/go.mod
- tools/go.sum
> Bump terraform-provider-aws from v2.18.0 to v2.20.0

- rules/awsrules/models/aws_secretsmanager_secret_invalid_policy.go
- rules/awsrules/models/aws_secretsmanager_secret_version_invalid_secret_string.go
- rules/awsrules/models/aws_ssm_maintenance_window_target_invalid_resource_type.go
- tools/go.mod
- tools/go.sum
- `aws_secretsmanager_secret_invalid_policy` rule
- Increase the upper limit from 4096 to 20480
- `aws_secretsmanager_secret_version_invalid_secret_string ` rule
- Increase the upper limit from 7168 to 10240
- `aws_ssm_maintenance_window_target_invalid_resource_type ` rule
- Allow `RESOURCE_GROUP` as a valid type
> Bump terraform-provider-aws from v2.20.0 to v2.22.0

- client/aws.go
- client/aws_test.go
- client/test-fixtures/assume-role.tf
- client/test-fixtures/shared-creds.tf
- client/test-fixtures/static-creds.tf
- docs/guides/credentials.md
- go.mod
- go.sum
- tflint/runner.go
Fixes #134 
This pull request introduces [`github.com/hashicorp/aws-sdk-go-base`](https://github.com/hashicorp/aws-sdk-go-base) and gets an AWS session in the same way as Terraform.
Also, it will take provider blocks in configuration files into account. For example, the following region settings are also propagated to TFLint, and redundant region settings are not required:
```hcl
provider "aws" {
region = "us-east-1"
}
```
However, this results in changing the priority of the credentials. This is an incompatible change. For example, regions and static credentials in the configuration file have higher priority than environment variables, so you need to set static credentials as a TFLint configuration. See the changed documentation for the new priorities.
In addition, ECS (CodeBuild) task …
> Get an AWS session in the same way as Terraform

- client/aws.go
- client/aws_test.go
- client/test-fixtures/assume-role.tf
- client/test-fixtures/shared-creds.tf
- client/test-fixtures/static-creds.tf
- tflint/config.go
- tflint/provider.go
- tflint/provider_test.go
- tflint/runner.go
- tflint/test-fixtures/provider_config/main.tf
Fixes #392 
See also #361 
There is a bug that returned an error when using a variable in the `provider` block attributes.
This pull request introduces `ProviderConfig` that contains the evaluation context. the `ProviderConfig` can be converted into `AwsCredentials` and initializes the client based on the credentials merged with TFLint's config.
> Eval provider attributes

- rules/awsrules/models/aws_spot_fleet_request_invalid_excess_capacity_termination_policy.go
The values the Terraform provider accepts are ["Default" and
"NoTermination"][spot_fleet_request_code].
[spot_fleet_request_code]: https://github.com/terraform-providers/terraform-provider-aws/blob/3f4ae7f126a63642e443d5e9ff09e8cec47823f9/aws/resource_aws_spot_fleet_request.go#L319-L320
> Fix values for excess_capacity_termination_policy

- Makefile
Now that Docker Hub's Automated Build is enabled, manual docker builds should be unnecessary.
> Remove image task from Makefile

- docs/guides/compatibility.md
- tools/go.mod
- tools/go.sum
No changes because the version of aws-sdk on which the provider depends does not change
> Bump terraform-provider-aws from v2.24.0 to v2.25.0

- docs/guides/compatibility.md
- tflint/runner.go
- tflint/runner_test.go
`path.module`, `path.root` and `path.cwd` are now available in TFLint 🎉
> Add support for `path.*` named values

- README.md
- cmd/cli.go
- cmd/cli_test.go
- cmd/option.go
- formatter/formatter.go
See #407 
This behavior is the default for new output formats.
> Remove `--quiet` option

- README.md
- cmd/cli.go
- cmd/cli_test.go
- cmd/option.go
- formatter/formatter.go
- formatter/pretty.go
The new output format includes a lot of colors, so it provides a `--no-color` option for users who cannot use it.
> Add `--no-color` option

- client/aws_ec2_mock.go
- client/aws_ecs_mock.go
- docs/guides/compatibility.md
- go.mod
- go.sum
- rules/awsrules/models/aws_cur_report_definition_invalid_s3_region.go
- rules/awsrules/models/aws_instance_invalid_type.go
- rules/awsrules/models/aws_launch_configuration_invalid_type.go
- rules/awsrules/models/aws_launch_template_invalid_instance_type.go
- rules/awsrules/models/aws_ssm_parameter_invalid_tier.go
- tools/go.mod
- tools/go.sum
Changed rules:
- `aws_cur_report_definition_invalid_s3_region` rule now allows `ap-east-1` as a valid value.
- `aws_instance_invalid_type`, `aws_launch_configuration_invalid_type` and `aws_launch_template_invalid_instance_type` rules now allow `i3en.metal` as a valid value.
- `aws_ssm_parameter_invalid_tier` rule now allows `Intelligent-Tiering` as a valid value.
> Bump terraform-provider-aws from v2.25.0 to v2.27.0

- .goreleaser.yml
To produce statically linked binaries even when not cross-compiling.
Related to https://github.com/wata727/tflint/issues/430.
> Disable CGO in GoReleaser

- docs/rules/terraform_dash_in_resource_name.md
- rules/terraformrules/terraform_dash_in_resource_name.go
This fixes unclear wording.
On a side note, the rationale to avoid dashes in names is because they make expressions `${var.instance-count-1}` unclear - it it hard to say if is subtraction `${var.instance-count - 1}` or just a reference to `instance-count-1` variable.
https://www.terraform.io/docs/configuration-0-11/interpolation.html#math
> Fix typo in dash rule

- rules/awsrules/aws_route_not_specified_target.go
- rules/awsrules/aws_route_specified_multiple_targets.go
- tflint/runner.go
- tflint/runner_test.go
If an expression includes invalid references, panic and exit instead of returning an error. The following configuration is an example:
```hcl
resource "aws_s3_bucket" "example" {
bucket = "example"
acl    = "private"
region = invalid // invalid reference
}
```
**Before**
```
Panic: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
-> 0: main.main.func1: /main.go(30)
-> 1: runtime.gopanic: /panic.go(679)
-> 2: github.com/wata727/tflint/tflint.isEvaluableExpr: /runner.go(677)
-> 3: github.com/wata727/tflint/tflint.(*Runner).EvaluateExpr: /runner.go(207)
-> 4: github.com/wata727/tflint/rules/awsrules.(*AwsS3BucketInvalidRegionRule).Check.func1: /aws_s3_bucket_invalid_region.go(75)
-> 5: …
```
> Fix panic when the expression includes invalid references

- README.md
- cmd/cli.go
- cmd/cli_test.go
- cmd/option.go
- cmd/option_test.go
- docs/guides/config.md
Fixes #438 
Note that `--disable-rule` behaves differently than `--ignore-rule`. Since `--ignore-rule` is deprecated, it was overridden by the value defined in `rule` blocks, but `--disable-rule` always takes precedence.
> Add `--enable-rule` and `--disable-rule` options

- rules/awsrules/aws_s3_bucket_invalid_acl.go
Add `aws-exec-read` ACL as a valid value to `aws_s3_bucket_invalid_acl` rule.
> Add aws-exec-read ACL as a valid value

- cmd/cli.go
- cmd/cli_test.go
- langserver/handler.go
- rules/provider.go
- rules/provider_test.go
Exit with an error when --enable-rule name is not found.
Also adds INFO level stats about total amount of rules and enabled rules.
> Check invalid rule names in command line options (fixes #470)

- rules/terraformrules/terraform_module_pinned_source.go
- rules/terraformrules/terraform_module_pinned_source_test.go
Bitbucket repos can be Git or Mercurial (for now, at least!), and Terraform can use either of them as a source.  If you were using a Mercurial Bitbucket repo as your module source, it would be reported as unpinned – even if you were pinning to a non-default Mercurial revision.
---
Spotted while working on #513.
> When checking if a source is pinned, allow for Mercurial/Bitbucket

- README.md
The docker image `terraform-linters/tflint` is not exist. Correct the name.
fix #529
> update the docker image name

- .pre-commit-hooks.yaml
The existing `pre-commit` configuration doesn't seem to work, as
`pre-commit` needs to be pointed to the compiled binary and not to
`main.go`. This commit fixes that and ensures `pre-commit` only tries to
lint terraform files.
> Fix the pre-commit hook

- tflint/loader.go
Resolves #554 
I didn't see how I could add an integration test for this, though.
> Parse absolute paths in TF_DATA_DIR correctly

- tflint/loader.go
While working on #555 I discovered that the `Root` field is no longer present in TF 0.12, so I think you could remove it:
https://github.com/hashicorp/terraform/blob/master/internal/modsdir/manifest.go#L19-L41
> Remove legacy TF 0.11 fields from module records

- .github/workflows/build.yml
- .github/workflows/generated_code_checks.yml
Set up [`actions/cache`](https://github.com/actions/cache) to speed up CI. Also, set up [`actions/upload-artifact`](https://github.com/actions/upload-artifact) to make easy to confirm the built binary in the pull request.
> Set up cache and artifact action

- docs/rules/README.md
- docs/rules/terraform_dash_in_output_name.md
- rules/provider.go
- rules/terraformrules/terraform_dash_in_output_name.go
- rules/terraformrules/terraform_dash_in_output_name_test.go
- I believe whilst the TF documentation does not cover outputs, the 'resource' best practices should also cover outputs (specifically no dashes/hyphens in output name).
- #567
> Feature: terraform_dash_in_output_name

- Dockerfile
go 1.13 change go111module auto setting behavior.
```
the auto setting now activates the module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file
```
https://golang.org/doc/go1.13#modules
So I think maybe this environment variable could be removed from Dockerfile.
> Remove go111module on env variable in Dockerfile.

- docs/rules/README.md
- docs/rules/terraform_deprecated_interpolation.md
- integration/variables/result.json
- integration/variables/template.tf
- rules/provider.go
- rules/terraformrules/terraform_deprecated_interpolation.go
- rules/terraformrules/terraform_deprecated_interpolation_test.go
Fixes #525 
This PR introduces a new rule `terraform_deprecated_interpolation`. This rule is enabled by default and will help you migrate to the next major version of Terraform.
> Add new terraform_deprecated_interpolation rule

- rules/awsrules/aws_resource_missing_tags.go
- rules/awsrules/aws_resource_missing_tags.go.tmpl
- rules/awsrules/aws_resource_missing_tags_test.go
Fixes #644 
`WalkResourceAttributes` walks only resources having "tags" definition. However, the rule should emit an issue even if there is no tags definition.
In this PR, the rule also walks resources even if the resource doesn't have tags definition.
/cc @bwhaley
> Emit an issue when there is no tags definition

- README.md
Windows users can also install `tflint` using Chocolatey: https://chocolatey.org/packages/tflint
```
choco install tflint
```
Equivalent to brew, but for Windows. 👍
> Add install guide for Windows (choco install)

- rules/awsrules/aws_s3_bucket_invalid_acl.go
The `bucket-owner-full-control` ACL is mentioned in AWS documentation: https://docs.aws.amazon.com/AmazonS3/latest/dev/example-walkthroughs-managing-access-example3.html#access-policies-walkthrough-cross-account-acl-acctB-tasks
Add it to the list of allowed ACLs.
> Add bucket-owner-full-control to allowed S3 ACLs

- docs/rules/aws_resource_missing_tags.md
- plugin/server.go
- rules/awsrules/aws_resource_missing_tags.go
- rules/awsrules/aws_resource_missing_tags.go.tmpl
- rules/awsrules/aws_resource_missing_tags_test.go
- tflint/runner.go
Fixes https://github.com/terraform-linters/tflint/issues/662
> Adds support for aws_autoscaling_group tag blocks and tags attributes

- rules/awsrules/aws_s3_bucket_invalid_acl.go
Similar to https://github.com/terraform-linters/tflint/pull/679, `bucket-owner-read` is not also invalid ACL.
Strictly speaking, these ACLs are for objects and are meaningless if specified on a bucket. Still, this ACL is not invalid.
> Add bucket-owner-read to allowed S3 ACLs

- docs/rules/README.md
- docs/rules/terraform_dash_in_data_source_name.md
- docs/rules/terraform_dash_in_module_name.md
- rules/provider.go
- rules/provider_test.go
- rules/terraformrules/terraform_dash_in_data_source_name.go
- rules/terraformrules/terraform_dash_in_data_source_name_test.go
- rules/terraformrules/terraform_dash_in_module_name.go
- rules/terraformrules/terraform_dash_in_module_name_test.go
Thank you for this awesome project!
* Add `terraform_dash_in_data_source_name` rule, which checks for dashes
in data source names
* Add `terraform_dash_in_module_name` rule, which checks for dashes in
module declarations
> Add dash checks for data sources and modules

- docs/rules/aws_resource_missing_tags.md
The current example doesn't make sense. Probably a copypasta error.
> Fixes the example of excluding resource types

- integration/jsonsyntax/result.json
- integration/jsonsyntax/template.tf.json
- integration_test.go
- tflint/loader.go
- tflint/test-fixtures/annotation_files/file.tf.json
Fixes #694 
Tokenize code to get annotations, but this only works for HCL syntax. If the extension is not `*tf`, skip this step.
> Skip to tokenize JSON syntax code

- docs/rules/README.md
- docs/rules/terraform_typed_variables.md
- rules/provider.go
- rules/terraformrules/terraform_typed_variables.go
- rules/terraformrules/terraform_typed_variables_test.go
This rule enforces that a type needs to be declared for variables. Enforcing this rule provides consistency across modules and ensures that engineers think about the type of variable being declared and makes it easier to consume the module knowing the type of the variable.
> Add a rule to enforce Terraform types for variables

- docs/rules/README.md
- docs/rules/terraform_required_providers.md
- rules/provider.go
- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_providers_test.go
This PR adds a rule that checks for `terraform.required_providers` and falls back to `provider.version` if set. It borrows copy from the Terraform docs:
https://www.terraform.io/docs/configuration/providers.html#provider-versions
> Add terraform_required_providers rule

- tflint/testing.go
As observed in #738, `AssertIssues` was not comparing the rule in an issue. Purely removing `IgnoreFields` is not an option because it causes panics due to unexported fields:
<details>
<summary>Panic output</summary>
```
--- FAIL: Test_TerraformModulePinnedSource (0.00s)
panic: cannot handle unexported field at {tflint.Issues}[0].Rule.(*terraformrules.TerraformModulePinnedSourceRule).attributeName:
"github.com/terraform-linters/tflint/rules/terraformrules".TerraformModulePinnedSourceRule
consider using a custom Comparer; if you control the implementation of type, you can also consider using an Exporter, AllowUnexported, or cmpopts.IgnoreUnexported [recovered]
panic: cannot handle unexported field at {tflint.Issues}[0].Rule.(*terraformrules.TerraformModulePinnedSourceRule).attributeName: …
```
> testing: compare Rule types and ignore struct fields

- docs/rules/README.md
- docs/rules/terraform_unused_declarations.md
- rules/provider.go
- rules/terraformrules/terraform_unused_declaration.go
- rules/terraformrules/terraform_unused_declarations_test.go
- tflint/runner.go
- tflint/runner_test.go
Declaring something and then not using it is typically either:
* A bug, and you need to reference it
* A leftover from removed code, and you can remove it
Variables, locals, and data sources are all declared inputs and if they are not direct referenced, they are effectively dead code. This rule works by:
* Copying the maps representing these values
* Visiting all expressions that could reference something, i.e. `resource`, `data`, `locals`, `provider`, `output`, and `module` blocks
* Examining each expression's variables and if they begin with a matched prefix (var, data, local),  deleting the corresponding pointer from the appropriate map
* Emitting any remaining pointers in each map as declared but unused
> Add unused_declarations rule

- integration/path/.terraform/modules/modules.json
- integration/path/main.tf
- integration/path/module/ec2.tf
- integration/path/result.json
- integration/path/result_windows.json
- integration_test.go
- tflint/runner.go
- tflint/runner_test.go
Fixes #733 
Closes #736 
I found that I was making a big mistake in building the eval context. According to the documentation, the `terraform.Evaluator`'s `Config` field should always be the root module, not the individual modules.
https://github.com/hashicorp/terraform/blob/v0.12.24/terraform/evaluate.go#L34-L35
The current implementation builds an Evaluator for each module and each module's evaluation context is treated as the root module. So, the values of `path.root` and` path.module` will always be the same.
This PR makes `path.root` to be evaluated correctly by building Evaluator and EvalContext for the root module.
> Build EvalContext as the root module

- .github/workflows/install_script.yml
- install_linux.sh
Allows any version of TFLint to be installed with install_linux.sh for E2E testing with the Ruleset plugin repository.
> Add support TFLINT_VERSION environment variable to installation script

- README.md
tflint-ruleset-azurerm has been released 🎉 
To make it easier to understand the support status of plugins for the Major Cloud, I added a support status to the README.
> Mention about other providers support

- cmd/cli_test.go
- cmd/inspect.go
- langserver/handler.go
- rules/awsrules/api/migration_test.go
- rules/awsrules/models/models_test.go
- rules/terraformrules/terraform_typed_variables.go
- rules/terraformrules/terraform_typed_variables_test.go
- tflint/loader.go
- tflint/loader_mock.go
- tflint/loader_test.go
- tflint/runner.go
- tflint/testing.go
- tflint/tflint_test.go
This PR adds an initial proof of concept of reading files, parsing as HCL/JSON, and then traversing the content based on a partial schema for exactly the attributes we want. It would close #741 and close #744. 
Happy to factor the parser/parsing into the runner as well. Just wanted to get this up and see if you're interested in this direction for this and similar rules.
> Expose raw hcl.File objects to rules

- rules/terraformrules/terraform_unused_declaration.go
- rules/terraformrules/terraform_unused_declarations_test.go
- rules/terraformrules/terraform_workspace_remote.go
- rules/terraformrules/terraform_workspace_remote_test.go
When visiting all expressions, we might encounter special attributes/blocks, where normal reference rules no longer apply:
https://www.terraform.io/docs/configuration/resources.html#meta-arguments
This currently returns an error for the `unused_declarations` and `workspace_remote` rules:
```
Error: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
```
Detecting these attributes seems too brittle/awkward, so simply exiting if an expression cannot be evaluated for references seems like the best fix
> ignore lang.ReferencesInExpr errors when walking all expressions

- docs/rules/README.md
- docs/rules/terraform_comment_syntax.md
- rules/provider.go
- rules/terraformrules/terraform_comment_syntax.go
- rules/terraformrules/terraform_comment_syntax_test.go
- tflint/runner.go
- tflint/runner_test.go
This PR adds a `terraform_comment_syntax` rule that enforces the canonical `#` comment style as described in the Terraform syntax guide:
https://www.terraform.io/docs/configuration/syntax.html#comments
This was requested by a colleague who noticed that @takescoop's Terraform configuration contains a mix of `#` and `//` comments but that Terraform clearly recommends `#`.
Since this is an aesthetic preference, the rule is disabled by default.
In order to accomplish this, I've added a `Files` method to the runner which returns all files in the current module. I'm interested in some other syntax-oriented rules that would depend on that method, e.g. enforcing canonical block padding:
```tf
resource "foo" "bar" {
attribute = "value"
block {
}
}
resource "foo" "baz" {
}
```
> add terraform_comment_syntax rule

- cmd/cli_test.go
- cmd/option.go
- cmd/option_test.go
- tflint/config.go
- tflint/config_test.go
- tflint/runner.go
- tflint/runner_test.go
Fixes #760 
In the rule configuration which is enabled with CLI, The `Body` attribute is always nil. So, it panics when decoded the rule configuration.
To prevent this, always set the empty body to the configuration.
> Make rule config which is enabled with CLI non-nilable

- install_linux.sh
Updating install_linux.sh for more readable and follow [google style](https://google.github.io/styleguide/shellguide.html) guide.
Here is the command which I use to check the format
`shfmt -d -i 2 -ci install_linux.sh`
> Update install linux script

- docs/rules/terraform_workspace_remote.md
Updates the documentation for the `terraform_workspace_remote` rule to indicate that it's safe to disable this rule if you don't use remote execution with your workspaces.
Closes #761
> terraform_workspace_remote: document disabling with local execution

- docs/rules/README.md
- docs/rules/terraform_deprecated_index.md
- rules/provider.go
- rules/terraformrules/terraform_deprecated_index.go
- rules/terraformrules/terraform_deprecated_index_test.go
This adds a rule that disallows the legacy dot/attribute syntax for accessing indexes in a list. This syntax was officially recommended in v0.11:
https://www.terraform.io/docs/configuration-0-11/interpolation.html
And because most official providers still use 0.11 syntax in their docs, I still see this used quite a bit:
https://www.terraform.io/docs/providers/kubernetes/r/service_account.html
https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html
It is no longer present in the 0.12 documentation and didn't even make the HCL spec:
https://github.com/hashicorp/hcl/issues/305
> add terraform_deprecated_index (disallows foo.0)

- docs/guides/extend.md
- plugin/discovery.go
- plugin/discovery_test.go
Fixes #781 
This PR adds the ability to change the plugin directory with the `TFLINT_PLUGIN_DIR` environment variable. This is useful when running TFLint in CI pipelines, Docker, etc.
> Change the plugins dir with TFLINT_PLUGIN_DIR environment variable

- go.mod
- go.sum
- plugin/server.go
- plugin/server_test.go
- tflint/terraform.go
- tflint/terraform_test.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/29
To allow the plugin to walk any block, add an API to the host process that returns a list of blocks.
> plugin: Add Blocks API

- tflint/runner_eval.go
- tflint/runner_eval_test.go
- tflint/runner_walk.go
Fixes #778 
If `count` is zero or `for_each` is empty, Terraform will not evaluate the attributes of that resource. On the other hand, TFLint tries to evaluate the expression of any attribute regardless of the meta-arguments. As a result, TFLint sometimes reports errors that are not reported by Terraform.
To avoid this problem, try to ignore resources that may not be evaluated when walking resource attributes and blocks. You may want to walk all the resources, whether they are evaluated or not, but I think we need to provide each API in that case.
> Do not walk resource attributes if the resource is not created

- docs/rules/README.md
- docs/rules/terraform_standard_module_structure.md
- rules/provider.go
- rules/terraformrules/terraform_standard_module_structure.go
- rules/terraformrules/terraform_standard_module_structure_test.go
- tflint/runner_test.go
- tflint/testing.go
This PR creates a rule that enforces the Terraform standard module structure:
https://www.terraform.io/docs/modules/index.html#standard-module-structure
The rule itself ensures that main, variables, and outputs file are created. It also ensures that variable/output blocks are included in the corresponding file. File checks are skipped for JSON-only projects and block checks are skipped when the declaration was in a JSON file. 
Outside of the rule implementation, I've also added logic to `TestRunnerWithConfig` that detects the directory so that rules can test configuration that is in a directory other than `.`.
> Add terraform_standard_module_structure rule

- tflint/config.go
I saw `raw.toConfig()` is been call on [L266](https://github.com/cedarkuo/tflint/blob/master/tflint/config.go#L266) & [L277](https://github.com/cedarkuo/tflint/blob/master/tflint/config.go#L277), but there are no value change behavior in between.
So I think maybe the return value can change to `cfg`?
If there any concern plz let me know, I will really appreciate of that. Thanks.
> Replacing loadConfigFromFile return func by cfg variable.

- rules/awsrules/tags/generator/main.go
Should resolve an issue where `go mod tidy` removes the provider dependency:
https://github.com/terraform-linters/tflint/pull/803#discussion_r443204793
> rename +build ignore constraint to "generators"

- README.md
Provides macOS install instructions that don't rely on `wget`, since it isn't installed by default (as described in #434). Continues to use `install` since that's always preferred over mucking with permissions directly.
Closes #434
> readme: replace wget w/ curl in macOS install example

- .github/ISSUE_TEMPLATE/bug_report.md
- docs/guides/compatibility.md
- go.mod
- go.sum
bump terraform to the latest, still a trivial change on the terraform side.
> chore(deps): bump terraform to v0.12.28

- go.mod
- go.sum
- plugin/encode.go
This brings the following changes:
- Added `Backend` to access the backend configuration
- Updated protocol version. This means all plugins will need to be rebuilt with the new SDK
For details, see the CHANGELOG of tflint-plugin-sdk.
> Bump tflint-plugin-sdk to v0.3.0

- docs/rules/terraform_required_providers.md
- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_providers_test.go
This PR updates the required providers rule to warn when a `provider` block specifies a `version` attribute. While this does have the effect of constraining the installed provider version, users should be moving to `required_providers` because declaring a new copy of the provider is likely to have unexpected effects for child modules.
New logic is:
* One issue is emitted for each provider _name_ that is missing from required_providers. If multiple providers for a given name are declared, the first text range will be used.
* One issue is emitted for each provider _instance_ that has a `version`, regardless of whether it also appears in `required_providers`.
This means that users moving from earlier versions with of Terraform with  `provider "foo" { version = "" }` in their configurations …
> terraform_required_providers: warn on provider.version

- integration/without_module_init/module.tf
- rules/terraformrules/terraform_deprecated_interpolation.go
- rules/terraformrules/terraform_deprecated_interpolation_test.go
This updates the `terraform_deprecated_interpolation` rule to use the `runner.WalkExpressions` method so that all expressions are evaluated rather than just resources and providers. This ensures that deprecated interpolations are also caught in locals, module calls, data sources, and outputs.
> deprecated_interpolations: evaluate all block types/expressions

- README.md
- cmd/option.go
- formatter/formatter.go
- formatter/junit.go
- formatter/junit_test.go
- go.mod
This PR adds support for JUnit output formatting, as supported by CircleCI, Jenkins, and others:
https://circleci.com/docs/2.0/collect-test-data/
I used ESLint's example output as a reference:
https://eslint.org/docs/user-guide/formatters/#junit
The JUnit structs come from github.com/jstemmer/go-junit-report, which handles all the XML details via struct tags.
Closes #786
> add support for --format junit

- go.mod
- go.sum
- plugin/encode.go
- plugin/server.go
- tflint/runner_walk.go
See the corresponding PR to the SDK this depends on:
https://github.com/terraform-linters/tflint-plugin-sdk/pull/50
Version constraints may be a bit different over the wire: the type exposed
by go-version can't necessarily be exactly reconstructed, as they've
been normalized under the hood. The original value is still accessible
through the usual hcl.Body.PartialContent or similar functions, if
needed.
In Terraform 0.12, I think the Count and ForEach struct members
will never actually be set, but the corresponding Terraform types have
them, so I've included them here. Maybe they'll Just Work once 0.13 is
out of beta and support is added to tflint.
> Expose `Server.ModuleCalls` for SDK

- rules/terraformrules/terraform_standard_module_structure.go
- rules/terraformrules/terraform_standard_module_structure_test.go
As reported in #834, the `terraform_standard_module_structure` was reporting false warnings when TFLint was invoked with a non-cwd directory:
```
$ /usr/local/bin/tflint -c /tmp/.tflint.hcl /tmp/ok
2 issue(s) found:
Warning: output "test" should be moved from /tmp/ok/outputs.tf to outputs.tf (terraform_standard_module_structure)
on /tmp/ok/outputs.tf line 1:
2: output "test" {
Reference: https://github.com/terraform-linters/tflint/blob/v0.17.0/docs/rules/terraform_standard_module_structure.md
Warning: variable "test" should be moved from /tmp/ok/variables.tf to variables.tf (terraform_standard_module_structure)
on /tmp/ok/variables.tf line 1:
1: variable "test" {
Reference: https://github.com/terraform-linters/tflint/blob/v0.17.0/docs/rules/terraform_standard_module_structure.md
``` …
> standard_module_structure: fix false positives when passing a directory

- go.mod
- go.sum
This brings the following changes:
- Added `WalkModuleCalls()` to access module calls
- Updated protocol version. This means all plugins will need to be rebuilt with the new SDK
For details, see the CHANGELOG of tflint-plugin-sdk.
> Bump tflint-plugin-sdk to v0.4.0

- docs/rules/terraform_naming_convention.md
- rules/terraformrules/terraform_naming_convention.go
- rules/terraformrules/terraform_naming_convention_test.go
Closes https://github.com/terraform-linters/tflint/issues/857
> Support custom formats in terraform_naming_convention rule

- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_providers_test.go
When the `terraform_required_providers` rule is used, it only detects providers with an explicitly declared provider block:
```tf
provider "foo" {}
```
To obtain all provider names, this PR also iterates through resources and data sources. For the reported range in the issue, it will use a:
1. Provider block
2. Resource block
3. Data source block
See #888
> required_providers: handle implicit providers

- rules/terraformrules/terraform_comment_syntax.go
- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_version.go
The comments for Check function for Terraform rules - terraform_comment_syntax, terraform_required_Providers and terraform_required_version has been updated to reflect the true intent.
Please approve the pull request such that the changes for these comments are reflected and go docs provides the right messages.
Thanks,
Ritesh
> Updated comments to reflect true intent of three methods

- go.mod
A recent PR added a `replace` directive to the `go.mod` file which makes `tflint` no longer gettable via `go get`.
Closes #833
> Remove replace directive

- go.mod
- go.sum
This brings the following changes:
- Added `Config()` to access the Terraform configuration
- Updated protocol version. This means all plugins will need to be rebuilt with the new SDK
For details, see the CHANGELOG of tflint-plugin-sdk.
> Bump tflint-plugin-sdk to v0.5.0

- .github/workflows/release.yml
- CHANGELOG.md
See https://github.com/terraform-linters/tflint/runs/1107925471
Go v1.15 drops supports of darwin/386. The release build of v0.20 is failing because older versions of goreleaser can't handle this correctly.
This pull request bumps goreleaser to the latest version and revise the v0.20 release notes.
> Bump goreleaser version

- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_providers_test.go
This provider is built in to Terraform rather than downloaded from the registry, therefore a required version would have no effect/meaning.
Closes #919
> terraform_required_providers: ignore terraform provider

- rules/awsrules/aws_s3_bucket_name.go
This rule warns of style issues, so this PR makes the rule disabled by default.
> Disable aws_s3_bucket_name rule by default

- README.md
tflint-ruleset-google has been released 🎉 
This PR updates provider support status about GCP provider.
> GCP support status is now experimental

- rules/awsrules/aws_resource_missing_tags.go
- rules/awsrules/aws_resource_missing_tags_test.go
Closes #949 
Fixes a bug where missing tags rule always fire when using dynamic blocks as tags for the AutoScaling Group.
Note that this is not an essential fix, but suppression of false positives. AutoScaling Groups with dynamic blocks are simply ignored because TFLint cannot expand dynamic blocks.
> missing_tags_rule: Suppress false positives when using dynamic blocks

- langserver/handler.go
- langserver/handler_test.go
- langserver/text_document_did_change.go
- langserver/text_document_did_open.go
When testing the Language Server feature in Windows I have discovered, that VSCode is sending file path as encoded URLs.
This results in paths like `C%3A/` instead of expected `C:/`, hence Language Server is yielding errors during `chdir`.
> escape language server paths

- go.mod
- go.sum
- integration/plugin/result.json
- integration/plugin/result_windows.json
- integration/plugin/template.tf.json
- tflint/terraform.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/69
HCL v2.7.0 has started to support parsing JSON config/expression partially. We can take advantage of this to achieve partial server/client transfers of JSON configuration syntax.
> plugin: Add support for JSON configuration syntax

- install_linux.sh
In GitHub Actions, if you set the matrix for multiple TFLint versions and set the corresponding `TFLINT_VERSION` environment variable, there is no way to set the "latest" version well.
This pull request allows "latest" as a valid `TFLINT_VERSION` value to handle this situation.
> chore: Allow "latest" as TFLINT_VERSION in the installation script

- cmd/inspect.go
- go.mod
- go.sum
- langserver/handler.go
- plugin/discovery.go
- plugin/plugin.go
- plugin/stub-generator/sources/bar/main.go
- plugin/stub-generator/sources/example/main.go
- plugin/stub-generator/sources/foo/main.go
- tflint/config.go
- tflint/config_test.go
- tflint/test-fixtures/config/plugin.hcl
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/72
This PR adds `Body` field with the `hcl:",remain"` tag to `tflint.PluginConfig`. This allows you to declare arbitrary custom attributes for each plugin, which previously only allowed `enabled` as attributes for the "plugin" block.
The content declared inside the "plugin" block will be transferred to the plugin as `hcl.Body`. On the plugin side, you can retrieve the configurations by decoding it against your own schema.
For example, the AWS ruleset will be able to declare the following configuration:
```hcl
plugin "aws" {
enabled = true
access_key = "AWS_ACCESS_KEY"
secret_key = "AWS_SECRET_KEY"
region     = "us-east-1"
profile    = "AWS_PROFILE"
shared_credentials_file = "~/.aws/myapp"
}
```
> plugin: Allow to declare custom attributes in config files

- go.mod
- go.sum
This brings the following changes:
- Added support for JSON configuration syntax
- Updated protocol version. This means all plugins will need to be rebuilt with the new SDK
For details, see the CHANGELOG of tflint-plugin-sdk.
> Bump tflint-plugin-sdk to v0.6.0

- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_providers_test.go
In Terraform 0.13+, all providers not in the `hashicorp` namespace that are loaded from the Terraform Registry require a `source`. This means a user might likely to have the following working config:
```tf
terraform {
required_providers {
datadog = {
source = "datadog/datadog"
}
}
}
```
The intent of this rule is to require modules to specify their provider _version_ requirements. Currently, the above is accepted since there's an entry in `required_providers`. Checking for a non-nil version constraint ensures that the version has been included in the provider source.
> terraform_required_providers: emit error when only source is specified

- rules/terraformrules/terraform_standard_module_structure.go
- tflint/runner.go
When TFLint is called with a relative path formatted with a leading `./`, results are empty from `Files()`. The logs I added for the rule that reproduced this printed:
```
$ tflint ./my/module
...
19:14:55 terraform_standard_module_structure.go:73: [DEBUG] 0 files found: map[]
```
`Clean` is called internally by `Dir`, meaning the comparison was `"my/module" == "./my/module"`. Cleaning both paths ensures the values are normalized for comparison.
The tests methods also call `Dir` to process a map of path -> file so adding a basic test didn't actually add coverage. 
But I did verify that it works as expected:
```
19:17:00 terraform_standard_module_structure.go:73: [DEBUG] 6 files found: map[backend.tf:0xc0001a0b40 main.tf:0xc0001a0f00 outputs.tf:0xc0001a0f80 providers.tf:0xc0001a1000 …
```
> runner: clean Terraform source path for comparison

- cmd/inspect.go
- go.mod
- go.sum
- langserver/handler.go
- plugin/encode.go
- plugin/server.go
- plugin/server_test.go
To cut out deep checking of AWS rules into a plugin, this PR extends runner API, adds `RootProvider` and `EvalExprOnRootCtx`.
In the ruleset plugin, an RPC server is assigned to each runner (module). If the target of the inspection is the root module, the provider configuration can be accessed, but the child module cannot access the provider configuration defined in the root.
To solve this problem, make use of the extended API to always have access to the root configuration.
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/79
> plugin: Extend runner API for accessing the root provider

- cmd/option_test.go
- go.mod
- go.sum
- plugin/server.go
- plugin/stub-generator/sources/example/main.go
- tflint/config.go
- tflint/config_test.go
- tflint/runner.go
To cut out the `aws_resource_missing_tags` rule into a plugin, this PR adds a new runner API, called `RuleConfig`.
This API returns an encoded HCL format rule config like the plugin configuration. See also https://github.com/terraform-linters/tflint/pull/967
On the plugin side, they can decode the rule config and reflects it into the config structure defined in the rule implementation using `gohcl.DecodeBody`.
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/82
> plugin: Add support for fetching rule config

- go.mod
- go.sum
- plugin/server.go
To cut out some rules into a plugin, this PR adds the `IsNullExpr` API. This is a wrapper of the `runner.IsNullExpr`.
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/85
> plugin: Add `IsNullExpr` API

- go.mod
- go.sum
- plugin/server.go
This PR adds the `File` runner API to work Language Server with plugins.
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/88
> plugin: Add `File` API

- docs/rules/README.md
- docs/rules/terraform_unused_required_providers.md
- rules/provider.go
- rules/terraformrules/terraform_unused_required_providers.go
- rules/terraformrules/terraform_unused_required_providers_test.go
As a complement to the "required providers" rule, this adds a rule that detects unused required providers. This ends up being slightly more complicated in the wild, since technically it's valid to put all your provider requirements in the root module, but it means `terraform init` may not work in child modules.
In theory this rule could also walk down the module tree looking for provider use, but I haven't implemented that here. This rule is disabled by default and users who specify required providers directly in each module can just turn it on.
> rule: terraform_unused_required_providers

- .github/dependabot.yml
- go.mod
- go.sum
TFLint uses github.com/spf13/afero as a filesystem abstraction. Terraform's configuration loading APIs accept an afero filesystem interface. Implicitly, this means TFLint and Terraform should use the same version of afero, but previously haven't done so.
In https://github.com/terraform-linters/tflint/pull/1004, updating afero to 1.5 added a `Chown` method, meaning implementers need to define that method. But if you're expecting `v1.2.2` as Terraform is, you haven't implemented that. Whether this means `Chown` should have gone in v2, 🤷🏻. But it results in build errors:
```
$ make test
go run ./plugin/stub-generator
go test -timeout 5m $(go list ./... | grep -v test-fixtures | grep -v vendor | grep -v aws-sdk-go)
../../go/pkg/mod/github.com/hashicorp/terraform@v0.14.3/configs/configload/load …
```
> deps: match afero version to terraform

- tflint/terraform.go
- tflint/terraform_test.go
`tflint.HCLBodyRange` is used to get the start position of the range in order to send `hcl.Body` to plugins. This implementation uses the filename extension to determine if it's native or JSON syntax, and gets each one in a rather unintuitive way.
However, there is a big problem with this assumption. First, `hclsyntax.Body` is not the only struct that satisfies `hcl.Body` in the` .tf` file. This method receives [`configs.mergeBody`](https://github.com/hashicorp/terraform/blob/f1be491e9731978508e339812cf92d4bbb795cb6/configs/module_merge_body.go#L22-L37) if resources were overridden.
Handling merged bodies is very difficult with the current implementation. First, `tflint.HCLBodyRange` should not return a single range, as it consists of multiple files and ranges. This PR changes the …
> tflint: Add workaround to get the range of `configs.mergeBody`

- cmd/cli.go
- cmd/cli_test.go
- cmd/option.go
- cmd/option_test.go
- tflint/config.go
- tflint/config_test.go
- tflint/runner.go
- tflint/test-fixtures/config/aws_credentials.hcl
- tflint/test-fixtures/config/config.hcl
- tflint/test-fixtures/config/deep_check.hcl
- tflint/test-fixtures/config/fallback.hcl
- tflint/test-fixtures/config/terraform_version.hcl
As AWS rules migrated to plugins in https://github.com/terraform-linters/tflint/pull/1009, remove the global deep checking option and AWS credentials configuration.
I plan to remove the relevant AWS rules implementation in another pull request.
> Remove global deep checking options

- plugin/encode.go
- plugin/server_test.go
Config() method causes panic when used in plugins if backend config is non-existent
Related:
terraform-linters/tflint-plugin-sdk#95
> Fix panic on empty backend in Config()

- go.mod
- go.sum
- plugin/encode.go
- plugin/server.go
When using Config() method with `--module` option you can get cty.unknownType inside module variables without default values and following error:
```
13:39:46 server.go:418: rpc: gob error encoding body: error encoding cty.Value: gob: type not registered for interface: cty.unknownType
```
This fix forces cty.Value{} in case of unknown value
> Fix gob encoder error on unknown value

- cmd/inspect.go
I'm working on a plugin which generates a list of rules dynamically,
based on its config:
https://github.com/richardTowers/tflint-ruleset-workspaces/
At the moment, it's not possible to refer to config in RuleNames because
that gets called before ApplyConfig. As a workaround, I've made my
plugin return the empty list for RuleNames:
https://github.com/richardTowers/tflint-ruleset-workspaces/blob/master/ruleset.go#L28
Naïvely, it looks like making the ApplyConfig a bit earlier would fix
this.
The tests pass, but I'm not sure if this will have unintended
consequences. Careful review would be much appreciated!
> Call ApplyConfig before ValidateRules

- .github/workflows/build.yml
Cache the results of Go builds in addition to modules. This should speed up the initial `go test` run in the `build` job.
> go: cache builds

- go.mod
- go.sum
- integrationtest/bundled/bundled_test.go
- integrationtest/bundled/disabled-rules/.tflint.hcl
- integrationtest/bundled/disabled-rules/result.json
- integrationtest/bundled/disabled-rules/template.tf
- integrationtest/bundled/rule-config/result.json
- tflint-plugin-sdk
- v0.8.0 => v0.8.1
- tflint-ruleset-aws
- v0.2.0 => v0.2.1
This update includes a bugfix about https://github.com/terraform-linters/tflint/issues/1054.
> Bump tflint-plugin-sdk and bundled plugins

- Dockerfile
Signed-off-by: Pujan Shah <pujan14@gmail.com>
Removed unused build tools from dockerfile and added default argument to image with CMD
> docker: remove unused build tools

- rules/terraformrules/terraform_naming_convention_test.go
This adds a test against the behavior claimed in #1068
Closes #1068, since the passing tests indicate that the rule is working correctly.
> terraform_naming_convention: test with count = 0

- cmd/cli.go
Per https://github.com/terraform-linters/tflint-ruleset-aws/issues/69#issuecomment-784701244, when users set a log level via `--loglevel`, plugin processes do not reflect this input. This passes it via `TFLINT_LOG`.
Longer term, removing `--loglevel` altogether would prevent this from being an issue. Terraform does not have a log level flag, perhaps in part in recognition that environment variables fit better with external plugin processes.
> pass --loglevel to plugins as TFLINT_LOG

- Dockerfile
- docs/developer-guide/building.md
See also https://github.com/terraform-linters/tflint/pull/1062
Update to Go 1.16 for Dockefile and the developer guide.
> Tweak about Go 1.16

- tflint/runner.go
- tflint/runner_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1063
`lang.ReferencesInExpr` returns variable references for the number of variable calls. In most cases, this is not a problem, but access to elements of the map also counts as a variable call, so multiple references may be returned for the same variable.
This PR avoids returning multiple references to the same variable by returning a map instead of a slice.
> tflint: Remove duplicate variable references

- go.mod
- go.sum
- integrationtest/bundled/bundled_test.go
- integrationtest/bundled/cty-based-eval/.tflint.hcl
- integrationtest/bundled/cty-based-eval/result.json
- integrationtest/bundled/cty-based-eval/template.tf
- plugin/server.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/83
See also https://github.com/terraform-linters/tflint-ruleset-aws/issues/48
In https://github.com/terraform-linters/tflint-plugin-sdk/pull/83, `EvalExprRequest` contains a detailed type, but TFLint server  doesn't use the passed type. This PR fixes this issue so that the value can be evaluated based on the type.
> plugin: Pass types to EvalExpr

- README.md
- cmd/option.go
- formatter/compact.go
- formatter/compact_test.go
- formatter/formatter.go
This PR adds a new formatter called `compact`. This is a simple output format that expresses an issue in one line, similar to the ESLint compact format:
```console
$ tflint -f compact
1 issue(s) found:
template.tf:11:19: Error - "invalid" is an invalid value as instance_type (aws_instance_invalid_type)
```
This format does not include the end line and end column, and the stacktrace for module arguments.
This is useful for regexp-based matching, such as the GitHub Actions problem matcher. See also https://github.com/terraform-linters/setup-tflint/issues/12
> formatter: Add support for --format compact

- go.mod
- go.sum
- integrationtest/bundled/bundled_test.go
- integrationtest/bundled/map-attribute/.tflint.hcl
- integrationtest/bundled/map-attribute/result.json
- integrationtest/bundled/map-attribute/template.tf
Attempts to reproduce #1102 in an integration test
> add integration test for map[string]string attr

- integrationtest/bundled/bundled_test.go
- tflint/config.go
Fixes https://github.com/terraform-linters/tflint/issues/1103
This PR fixes a crash when enabling a rule that requires config such as `aws_s3_bucket_name` with `--enable-rule`.
When rules are enabled from CLI, the pseudo rule configs are merged into the real configs. This should be ignored when merging, as pseudo rule configs have no reference to files.
> Fix crash when passed --enable-rule with a configured rule

- cmd/inspect.go
- cmd/version.go
- integrationtest/bundled/bundled_test.go
- langserver/handler.go
- tflint/config.go
- tflint/config_test.go
Similar to https://github.com/terraform-linters/tflint/pull/1105, it is crashed when passed `--only` with a configured rule.
```
% tflint --only aws_s3_bucket_name
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x186a197]
goroutine 38 [running]:
github.com/terraform-linters/tflint/tflint.(*RuleConfig).Bytes(...)
/Users/watanabekazuma/workspace/golang/src/github.com/wata727/tflint/tflint/config.go:430
github.com/terraform-linters/tflint/plugin.(*Server).RuleConfig(0xc00014de30, 0xc00017d7b0, 0xc0006ece70, 0x0, 0x0)
/Users/watanabekazuma/workspace/golang/src/github.com/wata727/tflint/plugin/server.go:167 +0x1b7
reflect.Value.call(0xc0007056e0, 0xc00015cc80, 0x13, 0x2735c99, 0x4, 0xc000613f08, 0x3, 0x3, …
```
> Fix crash when passed --only with a configured rule

- plugin/encode.go
- plugin/server_test.go
- tflint/runner_eval.go
- tflint/runner_eval_test.go
See #1112. These are typically normal, e.g. references to data source or resource attributes, or even locals (#571). The logs are optionally available if users want to try to understand why TFLint can or cannot validate a particular usage. Logs are still for internal introspection only and most users should never see them.
> Log at INFO level when TFLint cannot statically evaluate an expression

- tflint/terraform.go
- tflint/terraform_test.go
Fixes https://github.com/terraform-linters/tflint-plugin-sdk/issues/115
When encoding HCL bodies for sending to a plugin, the range of blocks is calculated from the contents of the body. However, if the body is empty, an empty range will be the return value of the `HCLBodyRange` func because there is no target range. Since the empty range doesn't have a filename, panic will occur when slicing source code bytes from the range:
https://github.com/terraform-linters/tflint/blob/015b01c7f149d11e253211a15a6db1e5b268c360/plugin/encode.go#L143
This PR avoids this panic by always setting the filename, even if the body is empty.
> tflint: Fix panic when encoding empty body

- go.mod
- go.sum
- rules/terraformrules/terraform_module_pinned_source.go
- rules/terraformrules/terraform_module_pinned_source_test.go
This PR refactors the `terraform_module_pinned_source` to remove:
* A lot of duplicated logic
* Complex regular expressions (replaced by URL/semver parsers)
* [Mercurial support](https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket) for Bitbucket, which they don't offer anymore
I'll bring in #1123 once I land this
> Refactor terraform_module_pinned_source rule

- docs/rules/terraform_module_pinned_source.md
- rules/terraformrules/terraform_module_pinned_source.go
- rules/terraformrules/terraform_module_pinned_source_test.go
Expands the list of default branches and allows users to configure additional branch names via config. Adapted from #1123. 
```hcl
rule "terraform_module_pinned_source" {
enabled = true
default_branches = ["dev"]
}
```
```hcl
module "unpinned" {
source = "git://hashicorp.com/consul.git?ref=dev"
}
```
```
Warning: Module source "git://hashicorp.com/consul.git?ref=dev" uses a default branch as ref (dev) (terraform_module_pinned_source)
```
Closes #1123
> terraform_module_pinned_source: support additional default_branches

- go.mod
- go.sum
- plugin/server.go
- plugin/server_test.go
**Abstract**
This PR exposes `Files()` method to [tflint-plugin-sdk](https://github.com/terraform-linters/tflint-plugin-sdk/issues/118). Current implementation already has the `File(filename string)` method exposed.
**Rationale**
Linting is the process of spotting potential errors. These errors can cause problems not only during the code execution but also to the business logic. Clean and organised files are often mandatory to maintainability. Some rules, however, make sense to one specific project or company. [tflint-plugin-sdk](https://github.com/terraform-linters/tflint-plugin-sdk) helps to extend _**tflint**_ in a way where each company can implement their own set of rules. 
**Use cases**
This PR exposes the `Files()` method in order to allow the developer to create more …
> Expose Files() runner method to Server

- docs/user-guide/plugins.md
- go.mod
- plugin/install.go
See also https://github.com/terraform-linters/tflint/issues/1142
There is a rate limit of 60 requests per hour by default. This PR adds the ability to set the `GITHUB_TOKEN` environment variable, you can use the PAT or GitHub Actions' token, etc to increase the rate limit.
> plugin: Allow authenticated requests via GITHUB_TOKEN

- README.md
This PR adds a link to the newly created [tflint-bundle](https://github.com/terraform-linters/tflint-bundle) image.
This image is one of the alternatives to bundled plugins and is mainly intended for use in super-linter.
See also https://github.com/terraform-linters/tflint/pull/1160
> Update README about Docker images

- plugin/discovery.go
- plugin/discovery_test.go
> fix: return error if plugin is not a file

- cmd/inspect.go
- cmd/version.go
- langserver/handler.go
For historical reasons, the "aws" plugin was available even if you didn't install the plugin, unlike other plugins. It is called "bundled plugins".
This PR will display a deprecation warning to end support for bundled plugins. The warning will be displayed if the following conditions are met:
- tflint-ruleset-aws was not installed
- Terraform configurations have declarations of aws resources (such as `aws_instance`)
This warning is output to stderr at runtime, etc. in the following format:
```console
$ tflint
WARNING: The plugin `aws` is not explicitly enabled. The bundled plugin will be enabled instead, but it is deprecated and will be removed in a future version. Please see https://github.com/terraform-linters/tflint/pull/1159 for details.
1 issue(s) found:
Error: "invalid" is an …
```
> plugin: Deprecate bundled plugins

- .github/workflows/install_script.yml
- install_linux.sh
Supports a custom install path, `$TFLINT_INSTALL_PATH`, with the previous path as the default. 
Fixes #1182
> install: allow passing `$TFLINT_INSTALL_PATH`

- rules/terraformrules/terraform_module_pinned_source.go
- rules/terraformrules/terraform_module_pinned_source_test.go
Adds additional validation that attempts to detect invalid URLs where the parsed hostname is empty.
Closes #1196
> terraform_module_pinned_source: detect invalid URLs

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/generated_code_checks.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- Dockerfile
- go.mod
Update to the [latest go1.17](https://blog.golang.org/go1.17)
> build: bump to use go1.17

- README.md
- docs/user-guide/plugins.md
Relates to #1160, the AWS plugin must be explicitly installed
> Remove bundled AWS plugin language from README

- cmd/cli.go
- docs/user-guide/config.md
Fixes #528 
Change the exit status to what I originally intended.
Before:
- 0: No issues found
- 2: Errors occurred
- 3: No errors occurred, but issues found
After:
- 0: No issues found
- 1: Errors occurred
- 2: No errors occurred, but issues found
This is clearly a breaking change, but due to its natural behavior, it may be worth accepting.
> cmd: Change exit status

- .github/workflows/goreleaser.yml
- .github/workflows/release.yml
GoReleaser v0.169.0 doesn't support darwin/arm64 build with Go 1.17.
https://github.com/goreleaser/goreleaser/issues/2412
As a result, v0.32.0 release doesn't include darwin/arm64 build. This PR updates the GoReleaser version to fix the issue.
> build: Update GoReleaser version

- rules/terraformrules/terraform_unused_required_providers.go
- rules/terraformrules/terraform_unused_required_providers_test.go
When a required provider is passed down to a module, the `terraform_unused_required_providers` rule still reports the provider as unused. This checks all provider configurations _explicitly_ passed into modules and counts those required providers as used. 
It remains a lint error to declare a required provider when it is _implicitly_ inherited by the child module, as that declaration is the child's responsibility.
Closes #1189
> `terraform_unused_required_providers`: handle module provider overrides

- rules/terraformrules/terraform_module_pinned_source.go
- rules/terraformrules/terraform_module_pinned_source_test.go
When using all of `go-getter`'s default detectors, GitLab URLs are detected and assumed to be Git URLs. This is not the case for users of GitLab's hosted Terraform registry:
https://docs.gitlab.com/ee/user/packages/terraform_module_registry/
It's also not how Terraform parses those URLs, which is the intent of the rule. Now the implementation matches Terraform.
Closes #1226
> terraform_module_pinned_source: do not assume gitlab URLs are git protocol

- README.md
- cmd/option.go
- formatter/formatter.go
- formatter/sarif.go
- formatter/sarif_test.go
- go.mod
- go.sum
Adds [SARIF](https://docs.oasis-open.org/sarif/sarif/v2.0/sarif-v2.0.html) as an output format. 
SARIF is nice as it is used (or understood) by GitHub code scanning as an input artifact, allowing Github to manage findings and annotate PRs, etc. I have found this very useful with tfsec, this PR is very much inspired by it.
The test suite crashes on my darwin system (though the formatter tests work fine). Fingers crossed they will run fine in GitHub actions, for now :)
> Adds SARIF as a supported output format

- tflint/config.go
- tflint/config_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1242
When enabling a plugin with `--enable-plugin`, plugin config such as version will be lost. This patch fixes the bug.
> tflint: Inherit config when plugins are enabled from CLI

- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
* Having a `go fmt` hook isn't that important, most users integrate this somewhere in their editor
* TFLint does not need to offer this if it's not straightforward and well-maintained. Someone contributed this in 2019 and it's not been touched.
Meanwhile, there are actively maintained suites of hooks out there with good support for TFLint, users should head there.
https://github.com/antonbabenko/pre-commit-terraform
> remove precommit hooks

- plugin/install.go
Helps users identify when they have set GitHub credentials that will be used for plugin downloads. If those credentials are invalid, subsequent requests will receive a 401.
Closes #1268
> plugin: log when `GITHUB_TOKEN` is set

- cmd/cmd_test.go
- integrationtest/bundled/bundled_test.go
- integrationtest/inspection/inspection_test.go
- integrationtest/langserver/langserver_test.go
- integrationtest/langserver/text_document_did_change_test.go
- integrationtest/langserver/text_document_did_open_test.go
- integrationtest/langserver/workspace_did_change_watched_files_test.go
- plugin/install.go
- rules/terraformrules/terraform_module_pinned_source_test.go
- rules/terraformrules/terraform_module_version_test.go
- rules/terraformrules/terraform_naming_convention_test.go
- rules/terraformrules/terraformrules_test.go
- terraform/lang/funcs/filesystem.go
- tflint/annotation_test.go
- tflint/terraform.go
- tflint/tflint_test.go
The `io/ioutil` package has been deprecated in Go 1.16 (See https://golang.org/doc/go1.16#ioutil). Since tflint has been upgraded to Go 1.17 (#1188), this PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.
> refactor: move from io/ioutil to io and os packages

- docs/rules/README.md
added in https://github.com/terraform-linters/tflint/pull/1182
> docs: linking terraform_module_version rule docs

- tflint/runner.go
- tflint/terraform.go
- tflint/terraform_test.go
Fixes #1281 
`TF_VAR_*` environment variables are parsed as string literals in TFLint. This behavior is the same as Terraform v0.11.x, but Terraform v0.12.x and later supports parsing env variables as HCL. The value passed in `--var` was already parsed as HCL, but the env variables were missing from that target.
This PR adds support for parsing `TF_VAR_*` env variables as HCL in the same way of Terraform v0.12.x and later.
> Parse TF_VAR_* env variables as HCL

- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_providers_test.go
Terraform has a system for built-in providers that are bundled with Terraform itself, most notably the `terraform` provider that handles `terraform_remote_state`. The [module testing experiment](https://www.terraform.io/language/modules/testing-experiment) uses a similar built-in provider. However, the `test` provider must also be specified in `required_providers` (unlike `terraform`), which causes the required provider version rule to report it as un-versioned. Built-in providers, by definition, cannot be versioned independent of Terraform.
Turns out the `addrs` package provides an API for checking this for a given provider. Using `IsBuiltIn` eliminates the need to check `name == "terraform"` and handles all built-in providers current and future.
Closes #1280
> `terraform_required_providers`: ignore builtin providers

- formatter/checkstyle.go
- formatter/compact.go
- formatter/formatter.go
- formatter/json.go
- formatter/json_test.go
- formatter/junit.go
- formatter/pretty.go
- formatter/sarif.go
- formatter/sarif_test.go
- integrationtest/inspection/bad-config/.tflint.hcl
- integrationtest/inspection/bad-config/result.json
- integrationtest/inspection/bad-config/template.tf
- integrationtest/inspection/enable-required-config-rule-by-cli/result.json
- integrationtest/inspection/inspection_test.go
- tflint/errors.go
Teach `--format json` and `--format sarif` to print structured error data. The former currently discards errors with severity warning, and the latter completely ignores `tferr`.
This PR is still in a draft stage (code complete, but missing unit/e2e tests) and is meant to solicit feedback on whether y'all think this makes sense or if you'd prefer to go in a different direction on this.
----
The context behind this PR is that I work on [`trunk`](https://trunk.io/products/check), a universal linter which makes it easy to set up and run linters for all the different types of tooling that developers use, and while looking into setting up `tflint` I was surprised that `--format default`, `--format json`, and `--format sarif` were returning wildly different things on an example repo (I was using …
> json,sarif: print structured error data

- integrationtest/inspection/conditional/.tflint.hcl
- integrationtest/inspection/conditional/result.json
- integrationtest/inspection/conditional/template.tf
- integrationtest/inspection/dynblock/.tflint.hcl
- integrationtest/inspection/dynblock/result.json
- integrationtest/inspection/dynblock/template.tf
- integrationtest/inspection/inspection_test.go
- integrationtest/inspection/provider-config/.tflint.hcl
- integrationtest/inspection/provider-config/result.json
- integrationtest/inspection/provider-config/template.tf
- plugin/stub-generator/main.go
- plugin/stub-generator/sources/customrulesettesting/custom/config.go
- plugin/stub-generator/sources/customrulesettesting/custom/ruleset.go
- plugin/stub-generator/sources/customrulesettesting/custom/runner.go
- plugin/stub-generator/sources/customrulesettesting/main.go
- plugin/stub-generator/sources/customrulesettesting/rules/aws_instance_example_type.go
- plugin/stub-generator/sources/testing/main.go
- plugin/stub-generator/sources/testing/rules/aws_s3_bucket_example_lifecycle_rule.go
This PR adds E2E test cases to help us migrate to the new plugin system. As far as I've noticed, the following three cases were not followed in the E2E test.
- Conditional resources
- https://github.com/terraform-linters/tflint/pull/785
- Dynamic blocks
- https://github.com/terraform-linters/tflint/pull/293
- Provider attributes evaluation
- https://github.com/terraform-linters/tflint/pull/393
> Add missing E2E test cases

- install_linux.sh
* add bash function to get architecture
* match arch to available download assets
I noted that `uname -m` will return aarch64 or aarch,
for arm based machines these changes will allow `os` var to match
multiple architectures and existing download assets.
Tested on darwin x86_64 (amd64), and linux amd64 and arm64.
> feat: get architecture for install

- .github/workflows/docker.yml
I noticed there's only a Docker image for `linux/amd64` and wanted to propose adding support for `linux/aarch64`. It's pretty useful to me as an Apple M1 and Docker Desktop user since I can get native performance out of tflint and avoid potential hiccups with x86_64 emulation. 😄
> Build Docker image for linux/aarch64

- .github/workflows/docker.yml
See also https://github.com/terraform-linters/tflint/pull/1206
Building for multi-platform on ubuntu will take longer than just building it for linux/amd64. The following build took 20 minutes:
https://github.com/terraform-linters/tflint/runs/5800029463?check_suite_focus=true
What we want to check in this test step is whether the Dockerfile is not broken. It is the responsibility of docker/build-push-action to ensure that multi-platform can be done correctly, and there is no need to check here.
This PR changes the build target to only linux/amd64 except for release. Also, for the above reasons, the linux/aarch64 test will be removed.
> build: CI only checks docker build for linux/amd64

- plugin/discovery.go
* Remove references to "API"
* Remove replacement of "client version" with "TFLint version"
* Mention potential resolutions (different core/plugin versions)
Closes #1341
If https://github.com/hashicorp/go-plugin/pull/191 is accepted this function can be re-written to not use string matching and could determine whether the supported client version(s) are "newer" or "older" than the server (plugin).
> discovery: reword message on protocol version err

- .github/workflows/release.yml
- .goreleaser.yml
- README.md
See https://github.com/terraform-linters/tflint/issues/1351
This PR adds the signatures for keyless signing when releasing a new version. GoReleaser has published an example of signging by [cosign](https://github.com/sigstore/cosign), which is used as a reference.
https://goreleaser.com/customization/sign/#with-cosign
In order to use GitHub Actions as an OIDC provider, the `id-token` permission is given. This will result in signing without manual authentication.
As far as I researched, cosign's keyless signing is an experimental feature, so added a warning to the README. For example, the following problems can be considered:
- The rekor.sigstore.dev and fulcio.sigstore.dev are operated on a best-effort basis and log entries may be reset without notice.
- …
> Add signatures for keyless signing

- cmd/init.go
- cmd/inspect.go
- cmd/option.go
- cmd/option_test.go
- cmd/version.go
- go.mod
- go.sum
- integrationtest/inspection/inspection_test.go
- langserver/handler.go
- langserver/workspace_did_change_watched_files.go
- plugin/server.go
- plugin/server_test.go
- rules/terraformrules/terraform_module_pinned_source_test.go
- rules/terraformrules/terraform_module_version_test.go
- rules/terraformrules/terraform_naming_convention_test.go
- tflint/config.go
- tflint/config_test.go
- tflint/runner.go
This PR refactors the implementation for `tflint.LoadConfig`. The `Config` functions have the following problems:
- Use `rawConfig` where all fields are pointers to check whether a field is set. However, pointers of primitive types may cause dereference errors.
- Config may have an `hcl.File` object for encoding, but It's not intuitive and it's easy to cause panic.
- `Merge` produces a deep copy of itself, but the deep copy implementation is redundant.
- `LoadConfig` always loads files from the file system, which makes it difficult to use for tests that require complex configs.
In this PR, I removed `rawConfig` and parsed it without using `gohcl` so that I could determine if the field was set while using the primitive type as it is. It is inspired by the implementation of the Terraform …
> Refactor tflint.LoadConfig

- go.mod
- go.sum
- integrationtest/inspection/conditional/result.json
- integrationtest/inspection/conditional/template.tf
- plugin/stub-generator/sources/testing/main.go
- plugin/stub-generator/sources/testing/rules/aws_iam_policy_example.go
- tflint/runner.go
See https://github.com/terraform-linters/tflint-plugin-sdk/pull/160
This PR allows you to accept the options added in https://github.com/terraform-linters/tflint-plugin-sdk/pull/160. In versions that do not include this fix, this option will be ignored, but otherwise it will work fine.
> plugin: Allow accepting IncludeNotCreated option

- README.md
- cmd/inspect.go
- cmd/option.go
- cmd/option_test.go
- docs/user-guide/config.md
- tflint/config.go
- tflint/config_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1343
This PR adds the `format` option to the config file. This option allows you to specify the format from the config file, similar to the CLI flags. The following is an example to configure the format as `compact`:
```hcl
config {
format = "compact"
}
```
> tflint: Add `format` option to the config file

- README.md
- cmd/cli.go
- cmd/option.go
Fixes https://github.com/terraform-linters/tflint/issues/1325
This PR adds a new `--color` option. This option forces colorized output to be enabled. Colored output is enabled by default, but is automatically disabled if a tty is not attached. The `--color` option always enables colorized output, even if the tty is not attached. You can see the behavior by output via a pipe.
```bash
$ tflint | less -R
$ tflint --color | less -R
```
> cmd: Add `--color` option

- tflint/runner.go
- tflint/runner_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1374
See https://github.com/terraform-linters/tflint/pull/1373
The fix in #1373 is the same as the [`GetRuleConfigContent`](https://github.com/terraform-linters/tflint/blob/6d02f853c5d945b94855ce94b879818d7eaea1dc/plugin/server.go#L55-L73), but it turns out that the `DecodeRuleConfig`, which is only used in Terraform rules, is not the same behavior.
Rules with a configuration cannot be enabled from the CLI, but Terraform rules can be enabled with the default config. This inconsistency will be fixed by https://github.com/terraform-linters/tflint/issues/1352.
> Fix unintended errors when enabling Terraform rules by CLI

- integrationtest/inspection/enable-plugin-by-cli/result.json
- integrationtest/inspection/enable-plugin-by-cli/template.tf
- integrationtest/inspection/inspection_test.go
- tflint/config.go
- tflint/config_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1375
In https://github.com/terraform-linters/tflint/pull/1365, the plugin's body enabled by CLI was changed from `hcl.EmptyBody` to nil. `hclext.Content` works fine for typed nil, but causes a panic on zero values. This PR makes that `Content` returns an empty body content without passing it to `hclext.Content`.
> Fix panic when enabling plugins by CLI

- install_linux.sh
`install -v` will already show the same thing:
Installing /tmp/tflint to /usr/local/bin/...
'/tmp/tflint' -> '/usr/local/bin/tflint'
tflint installed at /usr/local/bin/ successfully
> Remove a redundant log message

- terraform/addrs/module_source.go
- terraform/configs/check.go
- terraform/configs/config_build.go
- terraform/configs/configschema/implied_type.go
- terraform/configs/module_call.go
- terraform/configs/named_values.go
- terraform/configs/parser_config.go
- terraform/configs/provider.go
- terraform/configs/provider_validation.go
- terraform/configs/resource.go
- terraform/lang/funcs/cidr.go
- terraform/lang/funcs/collection.go
- terraform/lang/funcs/conversion.go
- terraform/lang/funcs/encoding.go
- terraform/lang/funcs/filesystem.go
- terraform/lang/funcs/number.go
- terraform/lang/funcs/redact.go
- terraform/lang/marks/marks.go
- terraform/lang/types/type_type.go
- terraform/lang/types/types.go
- terraform/terraform/evaluate.go
- terraform/terraform/variables.go
- terraform/tfdiags/diagnostic.go
- terraform/tfdiags/hcl.go
- terraform/version/version.go
- tflint/runner.go
- tflint/terraform.go
Fixes https://github.com/terraform-linters/tflint/issues/1388
See also https://github.com/hashicorp/terraform/releases/tag/v1.2.0 https://github.com/hashicorp/terraform/releases/tag/v1.2.1
This PR updates the bundled Terraform's internal packages version to v1.2.1 from v1.1.
This will allow you to use the new keywords such as `precondition`, `postcondition`, and `replace_triggered_by` added in v1.2.
Most of these changes were completed by simply copying the Terraform package, but it's worth noting that `terraform.DefaultVariableValues` has been removed in [this commit](https://github.com/hashicorp/terraform/commit/36c4d4c241b3402d7fbf677e4e7850f6ab80e66f).
However, if you look at the history of the change, it looks like it was removed when the Terraform core team removed the redundant …
> terraform: Add support for Terraform v1.2 syntax

- formatter/junit.go
- formatter/junit_test.go
https://www.ibm.com/docs/en/developer-for-zos/14.1.0?topic=formats-junit-xml-format
A JUnit `<failure>`'s text should contain:
- The text of the rule and the severity.
- The analysis provider and the analysis category.
- The source code file.
- The line number
The filename is currently missing. Additionally, `type` should also be set to the severity.
> formatter(junit): use standard range string in failure message

- tflint/runner.go
- tflint/runner_eval.go
- tflint/runner_eval_test.go
- tflint/runner_test.go
- tflint/test-fixtures/module_with_count_for_each/.terraform/modules/modules.json
- tflint/test-fixtures/module_with_count_for_each/module.tf
- tflint/test-fixtures/module_with_count_for_each/module/main.tf
Fixes https://github.com/terraform-linters/tflint/issues/1395
In Terraform, if `count = 0` or `for_each = []`, the module is not evaluated and the module arguments are also not evaluated. So, the following configuration is valid:
```hcl
variable "foo" {
type = object({ attr = string })
default = null
}
module "bar" {
source = "./baz"
count = 0
argument = var.foo.attr
}
```
However, TFLint ignores the module's meta-arguments, so in this case `var.foo.attr` was evaluated and an error occurred.
```
Failed to prepare rule checking; failed to eval an expression in module.tf:10; Attempt to get attribute from null value: This value is null, so it does not have any attributes.
```
This PR makes the evaluation of modules aware of the meta-arguments. In the above example, `var.foo.attr` is not …
> tflint: Skip evaluation of module arguments if the module call is not evaluated

- tflint/runner.go
- tflint/runner_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1412
If you pass a file path, TFLint will only report issues that match the passed file path from the inspection results for that directory. However, the file path is not normalized, so `./main.tf` and `main.tf` are treated as separate files.
```console
$ tflint main.tf
1 issue(s) found:
Warning: Interpolation-only expressions are deprecated in Terraform v0.12.14 (terraform_deprecated_interpolation)
on main.tf line 4:
4:   instance_type = "${var.foo}"
Reference: https://github.com/terraform-linters/tflint/blob/v0.37.0/docs/rules/terraform_deprecated_interpolation.md
```
```console
$ tflint ./main.tf
```
This PR fixes this problem by looking up the issues by a normalized path.
> cmd: Lookup issues by normalized path

- rules/terraformrules/terraform_deprecated_interpolation_test.go
- rules/terraformrules/terraform_workspace_remote.go
- rules/terraformrules/terraform_workspace_remote_test.go
- tflint/runner_walk.go
- tflint/runner_walk_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1257
Previously, `WalkExpressions` visited expressions based on the structure parsed by Terraform's internal API. Therefore, when the expression is nested in an expression such as map or list, there is an issue that it is not possible to walk the nested expression correctly.
This PR changes to use the HCL's native `Walk` function instead of the structure parsed by Terraform's internal API to walk expressions deeply. Note that this change will inspect the overridden configuration. This is because all files are inspected, regardless of Terraform semantics.
Also, there are some caveats when walking the JSON expressions. Unlike the native HCL syntax, the JSON syntax does not provide a `Walk` function, so we cannot walk for an expression …
> terraformrules: Walk map/list expressions deeply

- go.mod
- go.sum
- terraform/evaluator.go
- terraform/variable.go
- tflint/runner_eval_test.go
- tflint/runner_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1436
The Terraform evaluator no longer converts variables or applies default values in #1403.
https://github.com/terraform-linters/tflint/pull/1403/files#diff-2c53c5f250b940a59cca6fbb5c22a2ab9387a40b24b6c77375fd9aaa942f91cf
This merged Terraform v1.2 changes, commented as follows:
> d.Evaluator.VariableValues should always contain valid "final values" for variables, which is to say that they have already had type conversions, validations, and default value handling applied to them. Those are the responsibility of the graph notes representing the variable declarations. Therefore here we just trust that we already have a correct value.
This description is correct in Terraform, but not in TFLint. I will quote the Terraform architecture …
> terraform: Finalize variable values in Evaluator

- README.md
In Cosign v1.10, the `--certificate-github-workflow-repository` option has been added to allow verification of OIDC subject claims on certificates.
Ideally, it's better to get the certificate from Rekor (`COSIGN_EXPERIMENTAL=1`), but it's also safe if you can validate the certificate chain, even if downloaded individually from GitHub. We will adopt a way to download certificates individually because it is more stable.
> Update verification steps for the latest Cosign

- rules/terraformrules/terraform_required_version.go
- rules/terraformrules/terraform_required_version_test.go
Fixes a regression where multiple `terraform {}` blocks results in a false positive issue being emitted. https://github.com/terraform-linters/tflint/pull/1433/files#diff-0ec954b5c7913111444d96417f3325c4a2f5d91507770a89022bcbd4b05319cb, which rewrote chunks of the `terraformrules` package to eliminate dependencies on Terraform internals, introduced this regression. The new code, which operates on the generic HCL structure rather than the parsed Terraform internal representation has a simple logic error:
```go
for _, block := range body.Blocks {
if _, exists := block.Body.Attributes["required_version"]; !exists {
```
This processes every `terraform` block and emits and error if `required_version` is unset. Instead, the rule should process all the blocks and emit a single error if _none_ has …
> `terraform_required_version`: fix regression with multiple blocks

- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_providers_test.go
Fixes a regression, described in #1450. When evaluating an entry in `required_providers`, this adds a variable (dynamic value) with the provider's name, allowing the evaluation of `configuration_aliases`. This evaluation is looser than Terraform would perform, e.g., `configuration_aliases = [aws.foo.bar]` would presumably be considered valid. References to other providers should still fail.
Closes #1450
> `terraform_required_providers`: fix regression with `configuration_aliases`

- tflint/runner_eval.go
- tflint/runner_eval_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1447
When retrieving a value from a `cty.Value` marked as sensitive, the safety mechanism causes a panic. We avoid panic by unmarking in the same way as Terraform:
https://github.com/hashicorp/terraform/blob/v1.2.6/internal/terraform/eval_count.go#L61-L63
> Fix panic that occurs when using sensitive count

- rules/terraformrules/terraform_documented_outputs.go
- rules/terraformrules/terraform_documented_variables.go
- rules/terraformrules/terraform_module_pinned_source.go
- rules/terraformrules/terraform_module_version.go
- rules/terraformrules/terraform_naming_convention.go
- rules/terraformrules/terraform_required_providers.go
- rules/terraformrules/terraform_required_version.go
- rules/terraformrules/terraform_standard_module_structure.go
- rules/terraformrules/terraform_typed_variables.go
- rules/terraformrules/terraform_unused_declaration.go
- rules/terraformrules/terraform_unused_required_providers_test.go
- rules/terraformrules/terraform_workspace_remote.go
- rules/terraformrules/utils.go
Fixes https://github.com/terraform-linters/tflint/issues/1455
By default, the `GetModuleContent` API follows the Terraform semantics and does not return resources with `count = 0` or `for_each = []`. The same is true if these values cannot be evaluated (e.g. local value).
All resources can always be returned by using the `IncludeNotCreated` option. Terraform rules are more concerned with the definition and structure itself than whether the resource is created, so we should basically enable this option.
> terraformrules: Get module contents with `IncludeNotCreated: true`

- cmd/inspect.go
- integrationtest/inspection/eval-on-root-context/.terraform/modules/modules.json
- integrationtest/inspection/eval-on-root-context/.tflint.hcl
- integrationtest/inspection/eval-on-root-context/module.tf
- integrationtest/inspection/eval-on-root-context/module/template.tf
- integrationtest/inspection/eval-on-root-context/result.json
- integrationtest/inspection/inspection_test.go
- langserver/handler.go
- plugin/server.go
- plugin/server_test.go
- plugin/stub-generator/sources/testing/main.go
- plugin/stub-generator/sources/testing/rules/aws_route53_record_eval_on_root_ctx_example.go
- terraform/parser.go
- tflint/loader.go
- tflint/loader_mock.go
Fixes https://github.com/terraform-linters/tflint/issues/1468
https://github.com/terraform-linters/tflint/pull/1428 caused the gRPC server to only return files within the same module for `GetFile` requests. However, some examples of evaluating expressions in the root context may refer to files from other modules (especially the root module). From the above, the `GetFile` endpoint should be able to return all files regardless of module context.
In this PR, instead of returning the runner's parsed files (files in modules), return all the files loaded by the Loader. This allows `GetFile` to return arbitrary files regardless of module context.
> plugin: Return a file from other modules

- README.md
Verification by Cosign is not perfect. Currently, the `cosign verify-blob` command does not verify the certificate chain against the Fulcio root trust, so the attacker can replace `checksum.txt`, `checksum.txt.keyless.sig`, and `checksum.txt.pem`.
This way is the same as distributing a different public key for each release and having users download it. That is, verifiers must find a way to safely get `checksum.txt.pem` (in a different way than `checksum.txt`).
> Add a notice about verification of keyless signing

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/generate.yml
- .github/workflows/goreleaser.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- Dockerfile
- cmd/langserver.go
- docs/developer-guide/building.md
- go.mod
- langserver/handler.go
- langserver/text_document_did_change.go
- langserver/text_document_did_open.go
- langserver/workspace_did_change_watched_files.go
- plugin/checksum.go
- plugin/discovery.go
- plugin/install.go
- rules/terraformrules/utils.go
- tflint/runner.go
> deps: update to use go1.19

- rules/terraformrules/terraform_empty_list_equality.go
- rules/terraformrules/terraform_empty_list_equality_test.go
Fixes partially https://github.com/terraform-linters/tflint/issues/1424 to be able to also detect empty lists on more complex conditional expressions such as `var.enabled && var.proxy_subnets != [] ? 1 : 0`.
As @bendrucker referred [here](https://github.com/terraform-linters/tflint/issues/1424#issuecomment-1165980739), the evaluation of complex attribute values is a deeper issue (https://github.com/terraform-linters/tflint/issues/1257) and this PR does not fix that part.
> `terraform_empty_list_equality`: improve expression detection

- rules/terraformrules/terraform_unused_declaration.go
- rules/terraformrules/terraform_workspace_remote.go
- rules/terraformrules/terraform_workspace_remote_test.go
- rules/terraformrules/utils.go
Fixes https://github.com/terraform-linters/tflint/issues/1474
All expressions are now handled by `WalkExpressions` in #1432, so there are cases where reference parsing fails. For example, `ignore_changes` contains various keywords, which are invalid references.
Often these keywords are not expected and are ignored by `referencesInExpr`. However, if the name conflicts with an existing reference such as `data` or `terraform`, it may be misidentified as a valid reference and fail to parse.
This PR changes it so that it doesn't return diagnostics if it fails to parse, even for valid references like `data` and `terraform`. This might make it impossible to detect errors in valid references, but checking references is not the responsibility of this rule, so it makes sense to ignore them here.
> Ignore invalid references in referencesInExpr

- .github/workflows/build.yml
- .github/workflows/e2e.yml
- .github/workflows/generate.yml
- .github/workflows/goreleaser.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
This PR switches the Go version declaration in each workflow file to `go-version-file`.
https://github.com/actions/setup-go/pull/62
Additionally, enable the `cache` option to remove the dependency of actions/cache
https://github.com/actions/setup-go/pull/228
> build: Improve Go workflows

- formatter/compact.go
- formatter/compact_test.go
When `--formatter compact` is set and an error occurs that is/wraps `hcl.Diagnostics`, print each diagnostic in a format similar to the format used for issues raised by rules. In an environment like GitHub Actions where output is matched and associated with lines in a PR, this could help show syntax errors that prevented TFLint's execution in the context that triggered them.
The JSON and Sarif formatters similarly handle `hcl.Diagnostics` and while there's not much boilerplate more code could definitely be shared among the formatters in the future.
Closes #1461
> formatter(compact): print `hcl.Diagnostics` errors in compact format

- README.md
Reverts terraform-linters/tflint#1472
Cosign v1.11 now verifies the certificate chain by default when passing the `--cert` option. 
https://github.com/sigstore/cosign/pull/2139
The certificate must be generated on the GitHub Actions workflow of the `terraform-linters/tflint` repository, otherwise an error will occur for the malformed certificate. This leaves no room for spoofing the public key in a verification flow using Cosign.
The only attack surface is for an attacker to take control of this repository, delete existing releases, and recreate releases, which should be sufficiently difficult compared to traditional attack ways.
> Revert "Add a notice about verification of keyless signing"

- go.mod
- go.sum
- integrationtest/inspection/enable-config-rule-by-cli/.tflint.hcl
- integrationtest/inspection/enable-config-rule-by-cli/main.tf
- integrationtest/inspection/enable-config-rule-by-cli/result.json
- integrationtest/inspection/inspection_test.go
- integrationtest/inspection/rule-optional-config/.tflint.hcl
- integrationtest/inspection/rule-optional-config/main.tf
- integrationtest/inspection/rule-optional-config/result.json
- integrationtest/inspection/rule-required-config/.tflint.hcl
- integrationtest/inspection/rule-required-config/result.json
- plugin/server.go
- plugin/server_test.go
- plugin/stub-generator/sources/testing/main.go
- plugin/stub-generator/sources/testing/rules/aws_db_instance_with_default_config_example.go
- plugin/stub-generator/sources/testing/rules/aws_s3_bucket_with_config_example.go
Currently, The `GetRuleConfigContent` returns an error when the passed rule config is not found. However, this behavior is inconvenient when calling `DecodeRuleConfig` on rules with default config.
If the rule config is not found, the rule should just adopt the default config, but `DecodeRuleConfig` will fail because `GetRuleConfigContent` will return an error. In order to properly adopt the default config in this situation, you must correctly handle the "rule config not found" error returned by `GetRuleConfigContent`.
This PR changes the behavior of the `GetRuleConfigContent` API to simply return an empty body if the rule config is not found. This allows the caller of `DecodeRuleConfig` to not care whether the rule config exists.
Be careful with the behavior when there are required …
> plugin: Make GetRuleConfigContent doesn't return an error even if config not found

- integrationtest/inspection/inspection_test.go
- integrationtest/inspection/sensitive/.tflint.hcl
- integrationtest/inspection/sensitive/main.tf
- integrationtest/inspection/sensitive/result.json
- plugin/server.go
- plugin/server_test.go
- tflint/runner_eval.go
Fixes https://github.com/terraform-linters/tflint/issues/1457
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/174
When evaluating a variable with `sensitive = true`, TFLint fails with the following error:
```
Failed to check ruleset; Failed to check `aws_instance_previous_type` rule: value has marks, so it cannot be serialized
```
This happens because sensitive values are implemented as cty marked values. Marked values will cause an error when encoded in the message pack format to respond to plugins.
https://github.com/terraform-linters/tflint-plugin-sdk/blob/v0.11.0/plugin/plugin2host/server.go#L132
https://github.com/zclconf/go-cty/blob/v1.11.0/cty/msgpack/marshal.go#L45-L47
This behavior works very well with sensitive values and avoids unintentional disclosure …
> plugin: Fix an error when evaluating sensitive values

- README.md
- cmd/cli.go
- cmd/option.go
- integrationtest/cli/cli_test.go
See also https://github.com/terraform-linters/tflint/pull/1070
TFLint launches plugins as separate processes, so when setting log levels, an easy way to share between processes is to set an environment variable. As a matter of fact, currently, the log output is different depending on the setting with `--loglevel` and the setting with the `TFLINT_LOG` environment variable:
**TFLINT_LOG**
```
% cd integrationtest/inspection/basic
% TFLINT_LOG=trace tflint
15:18:12 config.go:115: [INFO] Load config: .tflint.hcl
15:18:12 config.go:242: [DEBUG] Config loaded
15:18:12 config.go:243: [DEBUG]   Module: false
15:18:12 config.go:244: [DEBUG]   Force: false
15:18:12 config.go:245: [DEBUG]   IgnoreModules:
15:18:12 config.go:249: [DEBUG]   Varfiles:
15:18:12 config.go:250: [DEBUG]   Variables: …
```
> Remove `--loglevel` CLI flag

- .github/workflows/release.yml
The current default is v1.10.1
https://github.com/sigstore/cosign-installer/blob/v2.5.1/action.yml#L13
> build: Use default cosign version

- Makefile
- integrationtest/bundled/bundled_test.go
- integrationtest/bundled/disabled_by_default/.tflint.hcl
- integrationtest/bundled/disabled_by_default/main.tf
- integrationtest/bundled/disabled_by_default/result.json
- tflint/config.go
See https://github.com/terraform-linters/tflint/issues/1513#issuecomment-1246414828
If the `terraform` plugin block is not declared in the config file, the "recommended" preset is applied implicitly. The `preset` config takes precedence over `disabled_by_default` declared in the config file, so counterintuitively, preset rules are not disabled.
This PR ignores the implicit default preset when `disabled_by_default` is enabled. This will prevent the preset from being applied.
> Ignore default preset by disabled_by_default

- README.md
- docs/user-guide/compatibility.md
TFLint now uses a fork instead of a specific version of Terraform internal packages. This PR updates the compatibility guide according to this fact.
> Update Terraform compatibility notices

- integrationtest/inspection/inspection_test.go
- integrationtest/inspection/just-attributes/.tflint.hcl
- integrationtest/inspection/just-attributes/result.json
- integrationtest/inspection/just-attributes/template.tf
- plugin/stub-generator/sources/testing/main.go
- plugin/stub-generator/sources/testing/rules/locals_just_attributes_example_rule.go
- terraform/module_test.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/201
This PR adds support for schema mode added by https://github.com/terraform-linters/tflint-plugin-sdk/pull/201. Actually, this support has already been merged in https://github.com/terraform-linters/tflint/pull/1525, so this PR adds tests to guarantee this support.
> plugin: Add support for schema mode

- README.md
See https://github.com/terraform-linters/tflint/discussions/1524#discussioncomment-3787986
The Chocolatey package is NOT directly maintained by the TFLint maintainers.
> Add notice about Chocolatey package

- cmd/inspect.go
- go.mod
- go.sum
- integrationtest/inspection/incompatible-host/.tflint.hcl
- integrationtest/inspection/incompatible-host/result.json
- integrationtest/inspection/inspection_test.go
- langserver/handler.go
- plugin/stub-generator/main.go
- plugin/stub-generator/sources/incompatiblehost/main.go
- tflint/meta.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/202
Add a step to get the version constraints set by plugins and check if the TFLint version satisfies it.
Note that version constraints are only available since tflint-plugin-sdk v0.14+. Since v0.12 and v0.13 are compatible in terms of protocol versions, these versions may return an unimplemented error. In this case, skip the check and continue inspection.
> plugin: Allow plugins to set TFLint version constraints

- integrationtest/inspection/expand/main.tf
- integrationtest/inspection/map-attribute/template.tf
- plugin/server.go
- plugin/server_test.go
- terraform/expandable.go
- terraform/lang/funcs/conversion.go
- terraform/lang/marks/marks.go
- terraform/module_test.go
As a limitation of go-cty, marked values cannot be serialized.
https://github.com/zclconf/go-cty/blob/v1.11.1/cty/msgpack/marshal.go#L45-L47
There are `IsMarked`/`HasMark` and `ContainMarked` methods for determining whether a value is marked, but the former cannot determine nested sensitive values such as objects. So returning a nested sensitive value will cause an error like https://github.com/terraform-linters/tflint/issues/1457.
This PR fixes it to determine with `ContainMarked` when serializing the value.
> Fix crash when evaluating nested sensitive values

- docs/developer-guide/api_compatibility.md
In protocol version 11, there are some compatibility notes between the SDK and TFLint.
This PR aims to reduce these considerations by documenting them.
> docs: Add API compatibility note

- .github/workflows/docker.yml
- Dockerfile
Currently, `docker build` for linux/arm64/v8 is emulated by QEMU. The problem with this method is that `go build` takes a lot of time.
Docker officially recommends using go cross-compilation instead.
https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/
Following this, we switch to an approach that integrates binaries built for linux/am64 and linux/arm64/v8.
> workflow(docker): Improve multi-arch image build

- terraform/evaluator.go
- terraform/evaluator_test.go
- tflint/runner.go
Fixes https://github.com/terraform-linters/tflint/issues/1565
Circular reference detection released in v0.42.0 is broken. The detection logic builds a call stack and determines that it is circular-referenced if the same address appears multiple times.
This call stack should literally be the stack. It should be popped after every push instead of clearing it at the end. The current detection logic detects erroneous circular references when the same local value appears multiple times in the middle.
```mermaid
graph LR
local.foo ---> local.bar
local.bar ---> local.baz
local.bar ---> local.baz
```
This PR fixes the detection logic by using the stack correctly.
> Fix incorrect circular reference detection

- terraform/evaluator.go
- terraform/evaluator_test.go
Follow up of https://github.com/hashicorp/terraform/pull/32027
> Convert variable types before applying defaults

- README.md
- SECURITY.md
Today, GitHub released [private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) 🎉 
We enable this feature in TFLint, set up a security policy, and tell users to use it to report vulnerabilities.
> Set up a security policy

- README.md
It seems that verify-blob with certificates (without chain) only works in experimental mode since some version.
If you disable experimental mode, you will get an error (Cosign v1.13.1):
```console
$ cosign verify-blob --certificate checksums.txt.pem --signature checksums.txt.keyless.sig --certificate-github-workflow-repository=terraform-linters/tflint checksums.txt
Error: verifying blob [checksums.txt]: certificate expired before signatures were entered in log: 2022-10-25T17:43:47Z is before 2022-11-14T14:28:18Z
main.go:62: error during command execution: verifying blob [checksums.txt]: certificate expired before signatures were entered in log: 2022-10-25T17:43:47Z is before 2022-11-14T14:28:18Z
```
Enabling experimental mode works fine.
```console
$ COSIGN_EXPERIMENTAL=1 cosign …
```
> Add COSIGN_EXPERIMENTAL=1 flag to the verification example

- terraform/parser.go
See also https://github.com/terraform-linters/tflint/discussions/1596
Fix panic caused by nil pointer dereference when `*.tf` file fails to load.
However, this error should be rare. If the file doesn't exist, an error occurs before `loadHCLFile`, so it seems to only occur in exceptional circumstances, such as filesystem corruption.
> Fix panic when file read fails

- .github/workflows/build.yml
Provides authentication when running tests in GitHub Action. Prevents flakes in plugin download tests due to rate limiting:
https://github.com/terraform-linters/tflint/actions/runs/3622249418/jobs/6106724062 (#1614)
```
--- FAIL: Test_Install (0.39s)
100
install_test.go:26: Failed to install: Failed to download checksums.txt.sig: GET https://api.github.com/repos/terraform-linters/tflint-ruleset-aws/releases/assets/35784141: 403 API rate limit exceeded for 20.36.167.160. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 20m57s]
```
> tests: pass `$GITHUB_TOKEN`

- .github/workflows/e2e.yml
- .github/workflows/install_script.yml
- install_linux.sh
A few days ago GitHub Actions started failing frequently. Although the detailed cause is unknown, it seems that the frequency of hitting the API rate limit on GitHub Actions is increasing.
In this PR, we pass `GITHUB_TOKEN` to e2e/install workflows to avoid rate-limiting. If the `GITHUB_TOKEN` is set in the install script, it will send a request with the token.
Also, there was another problem with the install script on the `hashicorp/terraform` container image. The cause of this is unknown, but it seems to be an Alpine Linux issue due to a missing curl-dev dependency. Added curl-dev and fixed the issue.
> chores: Fix flaky CI

- go.mod
- go.sum
- plugin/server.go
See https://github.com/terraform-linters/tflint-plugin-sdk/pull/224
This PR adds support for GetOriginalwd API added in https://github.com/terraform-linters/tflint-plugin-sdk/pull/224.
> plugin: Add support for GetOriginalwd API

- README.md
- cmd/cli.go
- cmd/init.go
- cmd/inspect.go
- cmd/option.go
- cmd/test-fixtures/arguments/README
- cmd/test-fixtures/arguments/example/test.tf
- cmd/test-fixtures/arguments/template.tf
- cmd/test-fixtures/arguments/test.tf
- cmd/version.go
- docs/user-guide/working-directory.md
- integrationtest/init/basic/.tflint.hcl
- integrationtest/init/init_test.go
Follow up of https://github.com/terraform-linters/tflint/pull/1622
This PR changes `--init` and `--version` to support the `--recursive` option. As a result `--chdir` is also supported:
```console
$ tflint --recursive --init
Installing plugins on each working directory...
====================================================
working directory: .
Plugin `aws` is already installed
====================================================
working directory: sub1
No plugins to install
====================================================
working directory: sub2
No plugins to install
====================================================
working directory: sub3
No plugins to install
====================================================
working directory: sub3/sub
No plugins to install
$ tflint …
```
> Add support for recursive init and print versions

- integrationtest/inspection/chdir/dir/main.tf
- integrationtest/inspection/chdir/dir/module.txt
- integrationtest/inspection/chdir/result.json
- integrationtest/inspection/chdir/result_windows.json
- terraform/loader_test.go
- terraform/parser.go
- terraform/parser_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1633
The `Parser.LoadConfigDir` will load a directory as if they were loaded from `baseDir`, regardless of the actual working directory. This is useful for getting relative paths from the original working directory, but `path.module` and `path.root` will give incorrect results if the module's `SourceDir` reflects the `baseDir`.
```console
$ cat dir/main.tf
locals {
content = file("${path.module}/text.txt")
}
$ cat dir/text.txt
This is file content
$ tflint --chdir=dir
// path.module is "dir", so "dir/dir/text.txt" is loaded.
```
This PR fixes `SourceDir` so that it returns the correct results:
```console
$ tflint --chdir=dir
// path.module is ".", so "dir/text.txt" is loaded.
```
As a side note, I noticed that I can't specify the …
> Fix path.module when using --chdir/--recursive

- README.md
- cmd/cli.go
- cmd/inspect.go
- cmd/option.go
- integrationtest/cli/cli_test.go
See also https://github.com/terraform-linters/tflint/pull/1636
This PR introduces the `--filter` option as an alternative to file arguments. This is the same as the file argument, except that it doesn't check for the existence of the file:
```console
$ tflint main.tf
$ tflint --filter=main.tf
```
Introduction of this option deprecates all arguments. It can be replaced as follows:
```console
$ tflint --chdir=dir                  # replacement of "tflint dir"
$ tflint --filter=main.tf             # replacement of "tflint main.tf"
$ tflint --chdir=dir --filter=main.tf # replacement of "tflint dir/main.tf"
```
Arguments are still available, but will be removed in a future version, so early migration to `--chdir`/`--filter` is recommended.
> Add --filter option

- plugin/discovery.go
Fixes https://github.com/terraform-linters/tflint/issues/1646
The `checkPluginExistance` does not expect loading errors other than `os.ErrNotExist`. As a result, it will panic if the plugin cannot be loaded for some other reason, such as permission denied.
> plugin: Fix panic when plugin path could not be loaded

- docs/user-guide/plugins.md
See also https://github.com/terraform-linters/tflint/issues/1181
Renovate now supports TFLint plugins. This PR mentions Renovate in the documentation, providing an opportunity for more users to take advantage of the automated update workflow.
> docs: Mention Renovate TFLint plugins support

- cmd/inspect.go
- cmd/option.go
- cmd/option_test.go
- tflint/config.go
- tflint/config_test.go
See also https://github.com/terraform-linters/tflint/issues/1604
The `tflint.Config` does not have a mechanism to distinguish between undefined and initial values, and whether or not it is overwritten was determined by whether it was different from the initial value.
https://github.com/terraform-linters/tflint/blob/16e02189fd8afb461a3941f11c2f4442f9e87602/tflint/config.go#L331-L333
However, this cannot override it to the initial value, and fails to achieve requirements like #1604.
This PR adds a flag to distinguish between undefined and initial values in `tflint.Config`. The `tfllint.Config` will only be overridden if the flag is set. With this change, the following five values can be overridden to the initial values:
- `module`
- `force`
- `disabled_by_default`
- `plugin_dir`
- `format` …
> tflint: Allow config to be merged even with initial values

- cmd/option.go
- cmd/option_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1604
This PR adds `--no-module` CLI flag. This flag enables you to disable module inspection from CLI.
> cmd: Add --no-module

- cmd/inspect.go
- integrationtest/cli/cli_test.go
See also https://github.com/terraform-linters/tflint/discussions/1650
This PR changes the arguments handling to reject all directory arguments (especially the current directory) with --chdir/--recursive. Previously, the current directory did not error when it should.
This is a preparation to warn when using all arguments in v0.46.
> cmd: Reject all directory arguments with --chdir/--recursive

- formatter/sarif.go
- formatter/sarif_test.go
Adds the TFLint version to the SARIF output. 
Avoids adding location information that is not known. Rules may emit violations about configuration that _wasn't_ present, meaning the `hcl.Range` may be a zero value, with no filename or position. Previously, a silly hack was in place that set the end line to 1 if it was zero.
Forces all paths to be POSIX-style with forward slashes, instead of `\` on Windows.
Closes #1657
> sarif: add tool version, exclude empty range/position, slash paths

- README.md
See https://github.com/terraform-linters/tflint/issues/1351
In preparation for the move to keyless signing, we are deprecating the signature verification with GPG keys. This PR removes the section about the GPG key from the README and encourages users to move to [cosign](https://github.com/sigstore/cosign).
The public key and signatures included in releases have not yet been removed. They will be supported until May 1, 2023, which is the key expiration date. After the expiration date, the key will not be updated and signatures by the GPG key will no longer be included in releases.
> Deprecate GPG key signed signature

- cmd/cli.go
- integrationtest/cli/cli_test.go
See also https://github.com/terraform-linters/tflint/pull/1612 https://github.com/terraform-linters/tflint/pull/1638
Previously, TFLint accepted files and directories as arguments.
```console
$ tflint main.tf
// print only main.tf issues from the directory
$ tflint modules/production
// inspect modules/production directory
```
This is a natural interface as a linter. However, as a Terraform language static analyzer, there are some issues.
First, the Terraform language must evaluate modules (directories), so it cannot evaluate a single file. This is clear if you imagine the example of evaluating an expression like `var.foo` in the presence of `variables.tf` and `main.tf` respectively.
Second, in the Terraform language, the current directory is included in the semantics. Imagine an example …
> cmd: Deprecate CLI arguments

- cmd/inspect.go
- go.mod
- go.sum
- langserver/handler.go
- plugin/server.go
- plugin/server_test.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/235
For historical reasons, errors from evaluating unknown or NULL values were handled on the server side rather than on the client side.
https://github.com/terraform-linters/tflint/blob/v0.45.0/plugin/server.go#L143-L167
But given that `EvaluateExpr` is an endpoint that returns a `cty.Value`, it's preferable to handle this error on the plugin side.
This PR changes to skip server-side error handling when the plugin's SDK is v0.16+. This is an internal change and has no end-user impact.
> plugin: Handle eval errors on the plugin side

- docs/user-guide/plugins.md
Rewrites the plugin rate limiting docs for clarity. In particular, this adds greater emphasis on the fact that GitHub rate limits anonymous requests by IP. In Actions, anonymous callers can potentially get a rate limiting error on their first request, entirely depending on the activity of other tenants on that Actions runner host.
See also https://github.com/terraform-linters/setup-tflint/issues/143
> docs: revise plugin rate limiting guide

- formatter/sarif.go
- formatter/sarif_test.go
Looks like https://github.com/terraform-linters/tflint/pull/1686/files accidentlly changed the End.Line to Start.Column
> serif: fix incorrect `endLine`

- cmd/inspect.go
- cmd/option.go
- docs/developer-guide/api_compatibility.md
- langserver/handler.go
- plugin/plugin.go
See also https://github.com/terraform-linters/tflint/pull/1727
This PR drops support for plugins built with SDK v0.12/v0.13.
SDK v0.13 is a version released over 6 months ago. It is in accordance with the future deprecation plan that versions that have passed more than 6 months since the release of the next version (v0.14) will be out of the scope of support. See https://github.com/terraform-linters/tflint/issues/1693 for details.
> plugin: Drop support for plugin SDK v0.12/v0.13

- plugin/install.go
- plugin/install_test.go
- tflint/config.go
- tflint/config_test.go
GitHub Enterprise Server is a private installation of GitHub. It provides a compatible API, but on a hostname other than `github.com`. This PR removes the requirement that plugin sources begin with `github.com` and assumes any other hostname is a GHES server hostname. If it's not, the client would likely receive a 404, which hopefully is enough "validation." But if needed, we could make a request an look for a header to explicitly fail with "this server is not GitHub."
I factored out the request logs into a logging transport to avoid the need to to reverse engineer URLs. Otherwise, `client.BaseURL.JoinPath` is the next best way to generate a URL relative to the client. 
Still thinking about how to test this. The only reasonable way would seem to be to run a mock server using `httptest` …
> plugin: support GitHub Enterprise Server as plugin source

- install_linux.sh
Use `-o` (overwrite) instead of `-u` (update).
Behaviourally, there shouldn't be any difference from this change.
This improves compatibility with BusyBox unzip, which only supports `-o`.
> fix(install_linux): Update unzip arguments

- terraform/addrs/resource.go
- terraform/lang/funcs/datetime.go
- terraform/lang/funcs/string.go
- terraform/lang/funcs/string_test.go
- terraform/lang/functions.go
- terraform/lang/functions_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1778
See also https://github.com/hashicorp/terraform/releases/tag/v1.5.0
This PR adds support for the following features added in Terraform v1.5:
- New functions: `plantimestamp`, `strcontains`
- https://github.com/hashicorp/terraform/pull/32980
- https://github.com/hashicorp/terraform/pull/33069
The major features in Terraform v1.5 are the import and check blocks, but TFLint does not depend on Terraform's schema, so no additional support is required.
> terraform: Add support for Terraform v1.5

- integrationtest/inspection/incompatible-host/result.json
- integrationtest/inspection/incompatible-host/result.json.tmpl
- integrationtest/inspection/inspection_test.go
Remove hard-coded versions from integration tests for release automation.
The `result.json.tmpl` file will be able to dynamically inject metadata using the `text/template` package.
> Remove hard-coded versions from integration tests

- go.mod
- go.sum
- plugin/discovery.go
- plugin/plugin.go
- plugin/server.go
- plugin/server_test.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/releases/tag/v0.18.0
This change causes the deprecated `IncludeNotCreated` option to be ignored.
> Bump tflint-plugin-sdk to v0.18.0

- go.mod
- go.sum
Fixes https://github.com/terraform-linters/tflint/issues/1791
Fixes https://github.com/terraform-linters/tflint/issues/1831
https://github.com/hashicorp/hcl/pull/617 fixes the issue of too large refinements.
https://github.com/hashicorp/hcl/pull/625 fixes the panic when applying optional attributes to dynamic values.
> Bump github.com/hashicorp/hcl to v2.18.0

- tflint/annotation.go
- tflint/annotation_test.go
Closes https://github.com/terraform-linters/tflint/pull/1752
The `tflint-ignore` annotation did not allow commas with spaces, even though the documentation shows examples.
```hcl
// invalid
// valid
```
But this is not what was intended, so we'll change this to work with commas with spaces as well.
The only incompatibility with this change is when using spaces to include comments. The example below was previously available as an `aws_instance_invalid_type` annotation, but with this change, it becomes `aws_instance_invalid_type This is comment`.
```hcl
```
> tflint: Allow commas with spaces in annotations

- .github/workflows/homebrew.yml
See https://github.com/terraform-linters/tflint/actions/runs/6065394790/job/16454840158
See https://github.com/mislav/bump-homebrew-formula-action/issues/58
GitHub Actions failed because the formula path changed in homebrew-core. This PR works around the issue by setting `formula-path`, as described in https://github.com/mislav/bump-homebrew-formula-action/issues/58.
> Add formula-path to follow formula path changes

- .github/workflows/lint.yml
- go.mod
- go.sum
- tflint/annotation.go
Go 1.21 introduces "slices" package.
https://tip.golang.org/doc/go1.21#slices
This allows you to remove the "golang.org/x/exp" package.
> Replace golang.org/x/exp/slices to slices package

- README.md
The tflint-bundle image was provided as a workaround when deprecating bundled plugins https://github.com/terraform-linters/tflint/pull/1164
Now, 2 years later, tflint-bundle hardly plays an important role anymore. You can use Renovate for automatic updates of plugins. The most recommended workflow is to set the plugin versions in `.tflint.hcl` and update it automatically.
As a first step, This PR removes tflint-bundle image in README. The tflint-bundle will be available for a while, but will gradually stop being updated.
> Deprecate tflint-bundle image

- .github/workflows/install_script.yml
Tests case where HTTP calls fail by passing a garbage version. There's some general messiness/legacy around error handling (a lot of checking of return values despite `bash -e`). This adds coverage before refactoring that all out.
See https://github.com/terraform-linters/tflint/discussions/1867
> add test coverage for install script fail

- .github/workflows/install_script.yml
- install_linux.sh
Ensure `install_linux.sh` still exists non-zero upon first error when the script is piped to bash (instead of run directly, which respects shebang).
> install: move `-e` out of shebang

- docs/user-guide/annotations.md
- tflint/annotation.go
- tflint/annotation_test.go
So that it is possible to add a reason why we ignore a rule.
Inspiration from [`nolintlint` linter](https://github.com/golangci/golangci-lint/blob/master/pkg/golinters/nolintlint/README.md).
> feat(annotations): Allow a comment at the end of a tflint-ignore annotation

- docs/user-guide/config.md
- docs/user-guide/environment_variables.md
- tflint/config.go
- tflint/config_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1828
This PR introduces a new environment variable called  `TFLINT_CONFIG_FILE`. This is a similar concept to [`TF_CLI_CONFIG_FILE`](https://developer.hashicorp.com/terraform/cli/config/environment-variables#tf_cli_config_file). This allows you to specify a config file without explicitly specifying it with `--config` option.
```console
TFLINT_CONFIG_FILE=config.hcl tflint
```
The environment variable has lower priority than `--config` option, and if they are set at the same time, the latter will be used. Similar to `--config` option, an error occurs if the file set by the environment variable does not exist.
> tflint: Allow config file to be set via `TFLINT_CONFIG_FILE`

- docs/user-guide/annotations.md
- tflint/annotation.go
- tflint/annotation_test.go
- tflint/runner_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1641
This PR introduces a new annotation syntax called `tflint-ignore-file`. The `tflint-ignore-file` annotation differs from the traditional `tflint-ignore` annotation in that it targets the entire file rather than a specific line. By declaring it at the top of a file as shown below, you can ignore all issues of the target rule that occur in that file.
```hcl
resource "aws_instance" "foo" {
instance_type = "t1.2xlarge"
}
```
If this annotation is declared anywhere other than at the top of the file, it will return an error.
> tflint: Add `tflint-ignore-file` annotation

- docs/user-guide/working-directory.md
See also https://github.com/terraform-linters/tflint/pull/1779
> docs: Remove mention of directory arguments

- cmd/inspect.go
After merging https://github.com/terraform-linters/tflint/pull/1918, errors are more likely to occur outside of the working directory as below.
```console
$ tflint --recursive
Failed to check ruleset; Failed to check `google_monitoring_alert_policy_invalid_combiner` rule: modules/monitoring/alert/variables.tf:155,1-42: Incorrect variable type; The resolved value of variable "gae_app_memory_usage_threshold" is not appropriate: list of object required.
```
This is an error that occurred in a called module and is difficult to fix because looking at `modules/monitoring/alert/variables.tf` doesn't tell you who called that module.
This PR adds the current working directory to the error output in recursive inspection to help troubleshoot such issues.
```console
$ tflint --recursive
Failed to …
```
> Print the working directory on error in recursive inspection

- cmd/option.go
- tflint/config.go
- tflint/config_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1926
Previously, the default configuration file name (`.tflint.hcl`) was treated specially and did not return an error even if explicitly passed the file does not exist.
```console
$ tflint --config .tflint.hcl
// no errors
$ tflint --config config.hcl
Failed to load TFLint config; failed to load file: open config.hcl: no such file or directory
```
This is inconsistent, so this change will always return an error.
```console
$ tflint --config .tflint.hcl
Failed to load TFLint config; failed to load file: open .tflint.hcl: no such file or directory
```
> Exit with an error if the explicitly passed `.tflint.hcl` does not exist

- cmd/init.go
See https://github.com/terraform-linters/tflint/pull/1934
This PR fixes an issue where newlines were not rendered properly as a result of turning double quotes into backticks.
> Avoid escaping newlines

- terraform/input_value.go
- terraform/input_value_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1877
See also https://github.com/hashicorp/terraform/blob/v1.5.7/internal/backend/unparsed_value.go
Previously assignments to undeclared variables was not an error, but this PR makes it an error:
```console
// Before
$ tflint --var foo=1
// No errors
```
```console
// After
$ tflint --var foo=1
Failed to parse variables; <value for var.foo>:1,1-1: Value for undeclared variable; A variable named "foo" was assigned, but the root module does not declare a variable of that name.:
Error: Value for undeclared variable
on <value for var.foo> line 1:
(source code not available)
A variable named "foo" was assigned, but the root module does not declare a variable of that name.
```
In most cases, the previous behavior will lead you to overlook …
> Make assignments to undeclared variables an error

- README.md
- cmd/inspect.go
- cmd/option.go
See https://github.com/terraform-linters/tflint/issues/1943
As explained in https://github.com/terraform-linters/tflint/issues/1943, inspections on module calls are performed sequentially, which can be slow if there are many calls. This PR improves speed by processing in parallel with goroutines.
This can be expected to speed up when you have many module calls. For example, with 50 module calls, we observed the following improvements:
```hcl
plugin "terraform" {
enabled = false
}
plugin "google" {
enabled = true
version = "0.26.0"
source  = "github.com/terraform-linters/tflint-ruleset-google"
}
```
```hcl
module "module" {
source = "./module"
count  = 50
}
```
```console
$ time tflint
real    0m0.774s
user    0m0.897s
sys     0m0.319s
$ time tflint --no-parallel-runners
real    0m1.591s …
```
> Enable per-runner parallelism

- terraform/loader.go
- terraform/test-fixtures/v0.15.0_module/module.tf
See also https://github.com/terraform-linters/tflint-ruleset-opa/pull/80
TFLint v0.50 now automatically calls local modules, so calling a module without a `source` attribute now causes a panic:
```console
$ cat main.tf
module "no_source" {}
$ tflint
Panic: unexpected module source type: <nil>
-> 0: main.main.func1: /main.go(25)
-> 1: runtime.gopanic: /panic.go(914)
-> 2: github.com/terraform-linters/tflint/terraform.(*Loader).LoadConfig.(*Loader).moduleWalkerFunc.func4: /loader.go(143)
-> 3: github.com/terraform-linters/tflint/terraform.ModuleWalkerFunc.LoadModule: /config.go(167)
-> 4: github.com/terraform-linters/tflint/terraform.buildChildModules: /config.go(106)
-> 5: github.com/terraform-linters/tflint/terraform.BuildConfig: /config.go(63)
-> 6: …
```
> Fix panic for module calls without source

- integrationtest/autofix/autofix_test.go
- integrationtest/autofix/chdir_with_conflict/dir/.tflint.hcl
- integrationtest/autofix/chdir_with_conflict/dir/main.tf
- integrationtest/autofix/chdir_with_conflict/dir/main.tf.fixed
- integrationtest/autofix/chdir_with_conflict/result.json
- integrationtest/autofix/chdir_with_conflict/result_windows.json
- plugin/server.go
- tflint/runner.go
- tflint/runner_test.go
Fixes https://github.com/terraform-linters/tflint/issues/1958
Autofix saves the fixed file in memory and writes them to the file system at the end. Therefore, if each rule always loads files from the file system, there is a problem that autofix that have been applied halfway cannot be properly reflected. To prevent this, TFLint's plugin server has the `GetFile` API that returns files based on auto-fixed code.
https://github.com/terraform-linters/tflint/blob/cc6168ccf8c14831c7bd6a09e16630a79120cec2/plugin/server.go#L73-L81
The auto-fixed code is applied in the runner by `runner.ApplyChanges`, so it can be retrieved in `runner.Files`.
However, there was a bug in `runner.Files` that prevented it from returning properly fixed files. As a result, it fell back to `GRPCServer.files` and returned …
> Fix a bug where auto-fixed code could not be retrieved via GetFile API

- plugin/server.go
- tflint/runner.go
- tflint/runner_test.go
When filtering emitted issues from child modules, ignore any issue covering an expression that cannot be parsed for references. Fixes a panic described in #1968.
`EmitIssue` may be called for a range that is not actually a valid Terraform expression. But TFLint just [checks](https://github.com/terraform-linters/tflint/blob/5ed807d0d4ab05fc81d9b3c9db623d3ee937ba2e/plugin/server.go#L213) whether the range's source is a valid _HCL_ expression. Something like `my_block` is a valid HCL expression, but it's not a valid expression in Terraform when it's a child block of a `resource`. Some declaration ranges (e.g., blocks with labels) are not valid HCL expressions either, but unlabeled block declarations (name, without braces) are syntactically valid expressions.
So `listVarRefs` must handle …
> Ignore module issues that are not valid expressions

- tools/release/main.go
`$EDITOR` should be handled as a shell command and not passed directly to exec.
VS Code, for example, needs $EDITOR to be set to `code --wait --new-window` to get the desired behavior.
> release: fix `$EDITOR` handling

- plugin/install_test.go
Missed in #1972 because Actions still uses Intel by default and doesn't offer larger runners without a paid org:
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners
Otherwise, `make test` fails on modern Macs:
```
--- FAIL: Test_Install (1.31s)
install_test.go:28: Failed to install: Failed to download tflint-ruleset-aws_darwin_arm64.zip: file not found in the GitHub release. Does the release contain the file with the correct name ?
```
> test: use darwin_arm64 compatible aws plugin

- Makefile
- docs/developer-guide/building.md
- terraform/loader_test.go
Documents the use of submodules for tests and automatically installs them via `make test`.
> test: document git submodule requirements

- .github/workflows/goreleaser.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- Dockerfile
- docs/developer-guide/building.md
- go.mod
- bump to use go1.22
- update base docker image
- update docs to specify go1.22
- enable caching everywhere `setup-go` is used
> feat: use go1.22

- install_linux.sh
Command output is piped into subsequent commands three places in this script (two `curl`s and one `dpkg`) and in all of them the script exiting with error, as requested with the existing `set -e`, would be preferable to silently succeeding if the curl or `dpkg` command fails to produce the expected text output.  The `--fail` option passed to curl both times, explicitly requests this behavior, but without `-o pipefail` it does not work.
> Set bash pipefail mode in install_linux.sh to catch curl errors

- formatter/sarif-2.1.0.json
- formatter/sarif_test.go
Adds the SARIF schema used to validate SARIF output in tests to the repository rather than downloading it via HTTP. We had some test failures due to 503s on schemastore.org:
https://github.com/terraform-linters/tflint/actions/runs/8144719629/job/22259423698?pr=1998#step:4:65
> sarif: add schema to repo

- docs/user-guide/plugins.md
- plugin/install.go
- plugin/install_test.go
Fixes https://github.com/terraform-linters/tflint/issues/2005
This PR adds support for host-specific GitHub tokens like `GITHUB_TOKEN_example_com`.
Previously, the `GITHUB_TOKEN` environment variable was supported during plugin installation for private repositories and to avoid rate limits. However, as explained in #2004 and #2005, when using GitHub.com and GHES together as plugin source hosts, there was a problem where different access tokens could not be used for each.
To solve this, we will introduce environment variables that are only used in GHES. For example, if a plugin is hosted on example.com, `GITHUB_TOKEN_example_com` will only be used when installing a plugin whose `source` is "example.com".
```hcl
plugin "foo" {
source = "github.com/org/tflint-ruleset-foo"
}
plugin "bar" { …
```
> plugin: Add support for host-specific GitHub tokens

- cmd/option.go
- tflint/config.go
Follow up of https://github.com/terraform-linters/tflint/pull/1918
The `--call-module-type` flag and the `call_module_type` attribute introduced in TFLint v0.50 have deprecated the `--module`/`--no-module` and the `module` attribute. To encourage migration to these, this PR adds warnings to stderr for the use of deprecated flags or attributes.
```console
$ tflint --module
WARNING: --module is deprecated. Use --call-module-type=all instead.
$ tflint --no-module
WARNING: --no-module is deprecated. Use --call-module-type=none instead.
$ tflint
WARNING: "module" attribute in .tflint.hcl is deprecated. Use "call_module_type" instead.
```
> Add warnings to --module/--no-module and `module` attribute

- go.mod
See https://github.com/terraform-linters/tflint/actions/runs/8924581586/job/24511211255?pr=1991
See https://github.com/golang/go/issues/62278
In Go 1.21+, it seems that the `go` directive in `go.mod` must specify the patch version.
I haven't been able to dig deeper into why it was working correctly so far, but it seems that at least the problem occurs when you use it with a module that specifies the patch version.
> Pin Go patch version in go.mod

- .golangci.yml
- plugin/install_test.go
Removes unnecessary loop variable copying
https://go.dev/blog/loopvar-preview
> go: remove loop variable copying

- integrationtest/inspection/functions/main.tf
- integrationtest/inspection/functions/result.json
- terraform/evaluator_test.go
- terraform/lang/funcs/terraform/functions.go
- terraform/lang/funcs/terraform/functions_test.go
- terraform/lang/functions.go
See also https://github.com/terraform-linters/tflint/pull/2030
I had overlooked https://github.com/hashicorp/terraform/pull/34830, so the names in development were being used as Terraform-specific function names. As a result, in TFLint v0.51 terraform-specific functions always return unknown values.
This PR fixes the function names so that the terraform-specific functions return the known values.
- https://developer.hashicorp.com/terraform/language/functions/terraform-encode_tfvars
- https://developer.hashicorp.com/terraform/language/functions/terraform-decode_tfvars
- https://developer.hashicorp.com/terraform/language/functions/terraform-encode_expr
> terraform: Fix `provider::terraform::*` function names

- .github/workflows/release.yml
- README.md
See https://github.com/terraform-linters/tflint/issues/1351
GitHub recently introduced Artifact Attestations.
https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
This PR adds a step to build Artifact Attestations in the release workflow. It's currently in public beta, so it's not recommended for all users, but it's simpler than Cosign, so you might want to migrate to it in the future.
In the future, we hope that Artifact Attestations will also be used for plugin verification.
> release: Introduce Artifact Attestations

- README.md
See https://github.blog/changelog/2024-06-25-artifact-attestations-is-generally-available/
GitHub Artifact Attestation is now GA. This PR removes the beta label from the README.
In the future, verification with Cosign will no longer be supported and users are encouraged to migrate to GitHub CLI.
> docs: Recommend verification with GitHub CLI

- cmd/cli.go
- integrationtest/recursive/chdir/result.json
- integrationtest/recursive/chdir/result_windows.json
- integrationtest/recursive/chdir/subdir1/.tflint.hcl
- integrationtest/recursive/chdir/subdir1/main.tf
- integrationtest/recursive/chdir/subdir1/subdir3/.tflint.hcl
- integrationtest/recursive/chdir/subdir1/subdir3/main.tf
- integrationtest/recursive/chdir/subdir2/.tflint.hcl
- integrationtest/recursive/chdir/subdir2/main.tf
- integrationtest/recursive/recursive_test.go
Fixes https://github.com/terraform-linters/tflint/issues/2051
Previously, `--chdir` and `--recursive` could not be used together.
```console
$ tflint --chdir=infra --recursive
Failed to find workspaces; cannot use --recursive and --chdir at the same time
```
This is because the `--recursive` was originally designed as `--chdir` for multi-directory https://github.com/terraform-linters/tflint/pull/1612 https://github.com/terraform-linters/tflint/pull/1622
Given this background, using them together was out of scope. Also, it is not obvious whether `--recursive` or `--chdir` takes precedence, which can lead to strange behavior when `--recursive` takes precedence.
However, given that `terraform -chdir=infra fmt --recursive` is a valid command, it is natural to expect similar behavior. In …
> cmd: Allow `--chdir` and `--recursive` to be used together

- formatter/checkstyle.go
- formatter/checkstyle_test.go
Fixes https://github.com/terraform-linters/tflint/issues/2056
Currently, the `checkstyle` output format uses the `rule` attribute as the rule name.
```console
$ tflint --format checkstyle
<checkstyle>
<file name="test.tf">
<error rule="test_rule" line="1" column="1" severity="error" message="test" link="https://github.com"></error>
</file>
</checkstyle>
```
However, the original Checkstyle XML output format uses the `source` attribute as the issue identifier.
https://github.com/checkstyle/checkstyle/blob/a7042e5119e6df9b8f782751af6cae2ee54a215a/src/main/java/com/puppycrawl/tools/checkstyle/XMLLogger.java#L205-L224
Several tools rely on the original format shown above, so TFLint adds the `source` attribute as well.
The `rule` attribute will remain for backwards compatibility, but will be …
> formatter: Add source attribute in the checkstyle format

- docs/user-guide/compatibility.md
- terraform/collections/set.go
- terraform/collections/set_test.go
- terraform/collections/unique_key.go
- terraform/collections/unique_key_test.go
- terraform/lang/funcs/filesystem.go
- terraform/lang/funcs/filesystem_test.go
- terraform/lang/funcs/string.go
- terraform/lang/funcs/string_test.go
- terraform/lang/functions.go
- terraform/lang/functions_test.go
Fixes https://github.com/terraform-linters/tflint/issues/2075
This PR adds support for the following features added in Terraform v1.9:
- New `templatestring` function
-  Don't panic if templatefile path is sensitive
> terraform: Add support for Terraform v1.9

- go.mod
- go.sum
- integrationtest/bundled/basic/result.json
- integrationtest/bundled/with_config/result.json
https://github.com/terraform-linters/tflint-ruleset-terraform/releases/tag/v0.8.0
> Bump bundled terraform ruleset to v0.8.0

- .github/workflows/e2e.yml
- Makefile
- integrationtest/race/eval_locals_on_root_ctx/.tflint.hcl
- integrationtest/race/eval_locals_on_root_ctx/main.tf
- integrationtest/race/eval_locals_on_root_ctx/module/main.tf
- integrationtest/race/eval_locals_on_root_ctx/result.json
- integrationtest/race/race_test.go
- terraform/evaluator.go
- terraform/evaluator_test.go
- terraform/lang/scope.go
- tflint/runner.go
Fixes https://github.com/terraform-linters/tflint/issues/2094
https://github.com/terraform-linters/tflint/pull/1944 parallelized the inspection of child modules, but did not take into account side effects that the child modules could cause on the root module. These are unsafe because the root module is shared by each child module (goroutine).
https://github.com/terraform-linters/tflint/blob/90494f35337ed3e024349e1ca6c88356045c96ee/cmd/inspect.go#L162-L174
The side effect reported in #2094 was the call stack. TFLint detects loops while building the call stack to prevent infinite loops when evaluating local values ​​with circular references. This call stack was shared per Runner (Evaluator).
https://github.com/terraform-linters/tflint/blob/a7ebc9b6592b599b628bcb9d3b0cc82047cd5f2a/terraform/e …
> Fix a race condition when evaluating on the root context

- formatter/sarif.go
- formatter/sarif_test.go
- go.mod
- go.sum
Update `owenrumney/go-sarif` to v2.3.3
Fixes #2017
> chore: Update to owenrumney/go-sarif/v2

- plugin/server.go
Follow up of https://github.com/terraform-linters/tflint/issues/2094
The bug in #2094 was fixed by #2096, but the problem of race conditions being prone to occur because the root runner is shared by multiple goroutines remains. Ideally, "Do not communicate by sharing memory; instead, share memory by communicating", but this would require significant design changes.
As a compromise, this PR changes the plugin API to acquire an explicit lock when performing operations on the root runner. This makes race conditions less likely to occur if side-effective operations are unintentionally introduced into the Runner API.
On the other hand, if multiple plugins perform frequent operations on the root runner, there is a risk of performance degradation. At least in most current cases, this is called …
> plugin: Introduce explicit locking on the root runner operations

- integrationtest/inspection/override/.tflint.hcl
- integrationtest/inspection/override/result.json
- integrationtest/inspection/override/template.tf
- integrationtest/inspection/override/template_override.tf
- integrationtest/inspection/override/version_override.tf
- plugin/stub-generator/sources/testing/main.go
- plugin/stub-generator/sources/testing/rules/terraform_required_providers.go
- terraform/module.go
- terraform/module_test.go
- terraform/parser.go
- terraform/parser_test.go
Fixes https://github.com/terraform-linters/tflint/issues/2114
As explained in #2114, the current override behavior is incomplete. The override behavior up to v0.53 is as follows:
- Attributes in blocks with matching headers (type and labels) are merged.
- Nested blocks are also merged recursively.
- If there are multiple blocks with the same header (e.g. `terraform`, `locals`), only one of them will be overridden. Which one gets overwritten is non-deterministic.
- The order in which override files are processed is completely random, not lexicographical.
```hcl
resource "aws_instance" "foo" {
instance_type = "t2.micro" # => Should be c5.xlarge, but can be m5.xlarge
ebs_block_device {
volume_type = "gp3"
volume_size = 20
}
}
resource "aws_instance" "foo" {
instance_type = "m5.xlarge" …
```
> Override exactly according to the Terraform spec

- go.mod
See https://github.com/terraform-linters/tflint/pull/2031
Previously, a patch version had to be pinned, but that no longer seems to be the case.
> go: Remove patch version from go.mod

- cmd/init.go
- integrationtest/init/init_test.go
With the current version of tflint, there can be a lot of output even when there are no changes. This PR moves the unneeded logs to DEBUG if there are no changes. 
Fixes https://github.com/terraform-linters/tflint/issues/2146
```bash
❯ tflint --recursive --config=$(pwd)/.tflint.hcl --init
Installing plugins on each working directory...
====================================================
working directory: dir1
Plugin "aws" is already installed
====================================================
working directory: dir2
Plugin "aws" is already installed
====================================================
working directory: dir3
Plugin "aws" is already installed
...
```
```bash
❯ ~/projects/dist/tflint --recursive --config=$(pwd)/.tflint.hcl --init
Installing plugins on each working …
```
> Move recursive init output to debug when there are no changes

- install_linux.sh
Handles GitHub API responses that do not include newlines. Previously, if the `releases/latest` response lacked newlines within its JSON, `get_latest_release` would return `mentions_count` since that is the last double-quoted string on the line grep matched (the whole object).
Now, `sed` will only capture the string value after `"tag_name"`. It looks past a colon and optional surrounding whitespace and captures the next double quoted group. This is compatible with both compact and multiline JSON.
We still need `grep` to handle multiline JSON, since we need to exclude all lines other than the one we want. Otherwise the output is the original object with a single malformed line containing the latest version. GNU `sed` can handle multiline input with `-z` so keeping `grep` for that preserves …
> install: handle GitHub API JSON without newlines

- docs/developer-guide/api_compatibility.md
- plugin/plugin.go
- plugin/server.go
- plugin/server_test.go
- terraform/tfhcl/expand_body.go
This PR drops support for plugins built with SDK v0.14/v0.15.
SDK v0.15 was released two years ago and this change is in line with the deprecation plan. This allows plugins to handle `cty.Value` ​​except for ephemeral values.
> plugin: Drop support for plugin SDK v0.14/v0.15

- cmd/init.go
- integrationtest/init/init_test.go
Follow up of https://github.com/terraform-linters/tflint/pull/2150
The `strings.Builder`-based approach is complicated to implement, so we'll change it to a simpler output.
No changes
**Before**
```console
$ tflint --init
Plugin "aws" is already installed
Plugin "google" is already installed
```
**After**
```console
$ tflint --init
All plugins are already installed
```
**Before**
```console
Installing plugins on each working directory...
====================================================
working directory: .
No plugins to install
====================================================
working directory: subdir
Installing "aws" plugin...
Installed "aws" (source: github.com/terraform-linters/tflint-ruleset-aws, version: 0.34.0)
====================================================
working …
```
> cmd: Simplify recursive init outputs

- plugin/install.go
Fixes https://github.com/terraform-linters/tflint/issues/2209
See also https://github.com/terraform-linters/tflint/pull/2159
The keyless verification of plugins introduced in v0.55 is intended for public repositories and does not work properly for private repositories. Artifact attestations generated in private repositories do not include transparency logs, and the issuer of the certificate is GitHub, Inc, not sigstore.dev.
We can configure a policy to allow you to verify artifact attestations generated in private repositories by following the GitHub CLI, but given the plan limitations on the use of artifact attestations in private repositories, it may be difficult to enforce it in the future.
Given that the risk of plugin tampering in private repositories is lower than in public …
> plugin: Skip keyless verification for private third-party plugins

- install_linux.sh
For the purposes of tflint arm64 and aarch64 are equivalent and so we don't need to keep the logic that checks for the user space being 32 bit. This allows us to not rely on dpkg being installed, but more importantly stops 64 bit systems from falling back to 32bit tflint install when dpkg is not present
> Remove dependency on dpkg in install_linux.sh

- .github/dependabot.yml
These frequently hit merge conflicts with `go.mod` since they are heavily inter-dependent.
https://go.dev/wiki/X-Repositories
> dependabot: group golang.org/x/* deps

- README.md
A PR was never made from the discussion at https://github.com/terraform-linters/tflint/discussions/2207 therefore i'm opening up one.
This PR aims to update the readme providin instructions about how to init before running tflint with docker
Please let me know if there's anything you would like me to change
> docs: Update docker readme example

- cmd/inspect.go
- docs/user-guide/annotations.md
- langserver/handler.go
- tflint/annotation.go
- tflint/annotation_test.go
I have a use case where I'm generating `.tf.json` files for a bunch of different root modules; these `.tf.json` files define several locals for convenience, which may or may not be used by the root modules they're placed in. I wanted to be able to ignore the `terraform_unused_declarations` rule without disabling it globally, but I realized that there wasn't a way to do this since the annotation system didn't support JSON files at all. This change adds limited support for `tflint-ignore-file` annotations in a top-level comment property.
> Add support for tflint-ignore-file annotations in JSON

- .github/workflows/build.yml
- .github/workflows/docker.yml
- .github/workflows/e2e.yml
- .github/workflows/generate.yml
- .github/workflows/goreleaser.yml
- .github/workflows/homebrew.yml
- .github/workflows/install_script.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
See also https://www.wiz.io/blog/new-github-action-supply-chain-attack-reviewdog-action-setup
Follow up of https://github.com/terraform-linters/tflint/pull/2102
Run `pinact run` with v1.4.0.
https://github.com/suzuki-shunsuke/pinact
> Update pinned GitHub Action versions

- .github/workflows/lint.yml
- .golangci.yml
- plugin/discovery.go
- tflint/annotation.go
https://ldez.github.io/blog/2025/03/23/golangci-lint-v2/
* Ran `golangci-lint migrate` to migrate config
* Ran `golangci-lint run ./... --fix` to apply auto-fixes
> golangci-lint v2

- .github/workflows/build.yml
- go.mod
- go.sum
Uses [`govulncheck`](https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck) to check each build for known Go vulnerabilities in the source.
Inspired by https://github.com/opentofu/opentofu/pull/2600, this attempts to cut through the steady drip of noisy automated reports. Where most automated reports detect inclusion of a vulnerable dependency version via package manifests (`go.mod`, `go.sum`), `govulncheck` analyzes the source code for use of vulnerable _symbols_. This has a dramatically higher signal to noise ratio. Reports from `govulncheck` should often be actionable and require an advisory. Anything not reported is most likely noise and does not merit an advisory. 
Uses the new `go tool` features in Go 1.24 to invoke the command.
> go: use `govulncheck` to detect security issues

- terraform/tfhcl/expand_spec.go
Fixes https://github.com/terraform-linters/tflint/issues/2243
See also https://github.com/hashicorp/hcl/issues/737
The `hcl.DiagnosticTextWriter` has an issue where it will panic when writing out a diagnostic that has an expression containing a marked value.
TFLint can run into this issue when expanding the `for_each` meta-argument with a sensitive value. If the `for_each` is not  iterable (it is not iterable if marked), a diagnostic containing the expression context of the `for_each` is created and written to stderr by the `DiagnosticTextWriter`.
Hopefully this will be fixed in upstream, but here's a workaround to prevent the panic by excluding expression context from the  diagnostic when the `for_each` is marked.
By the way, other cases that include expression context in diagnostics do …
> Exclude expression context from marked `for_each` diagnostics

- tools/release/main.go
Potential fix for [https://github.com/terraform-linters/tflint/security/code-scanning/12](https://github.com/terraform-linters/tflint/security/code-scanning/12)
To fix the issue, the dot (`.`) in the regular expression should be escaped to ensure it matches a literal dot rather than any character. This can be done by replacing `.` with `\.`. Additionally, using a raw string literal (enclosed in backticks) for the regular expression is recommended to avoid the need for double escaping backslashes.
Specifically, the regular expression on line 23 should be updated from:
```go
`github.com/terraform-linters/tflint-ruleset-terraform v(.+)`
```
to:
```go
`github\.com/terraform-linters/tflint-ruleset-terraform v(.+)`
```
This ensures that the pattern matches only the intended domain `github.com` …
> Potential fix for code scanning alert no. 12: Incomplete regular expression for hostnames

- tools/release/main.go
Potential fix for [https://github.com/terraform-linters/tflint/security/code-scanning/11](https://github.com/terraform-linters/tflint/security/code-scanning/11)
To fix the issue, the dot (`.`) in the regular expression should be escaped to ensure it matches a literal dot rather than any character. This can be done by replacing `.` with `\.`. Additionally, using a raw string literal (enclosed in backticks) avoids the need to double-escape the backslash, making the regular expression more readable. The corrected regular expression will be:
```
`github\.com/terraform-linters/tflint-plugin-sdk v(.+)`
```
This change ensures that the regular expression matches only the intended domain `github.com` and not any other unintended strings.
---
_Suggested fixes powered by Copilot Autofix. Review …
> Potential fix for code scanning alert no. 11: Incomplete regular expression for hostnames

- terraform/evaluator.go
- terraform/evaluator_test.go
- terraform/lang/scope.go
Fixes https://github.com/terraform-linters/tflint/issues/2287
In cases such as `Invicton-Labs/deepmerge`, where a chain of local values is evaluated nearly 100 times, there is an issue with TFLint's evaluation strategy of evaluating local values each time, which makes it very slow.
To prevent this, we add a cache of evaluated local values to `lang.Scope` as `ResolvedLocalValues` and have `GetLocalValue` return the cache instead of re-evaluating the expression.
As a side effect, impure function calls like `uuid()` will be cached to the first evaluation result instead of being called every time:
```hcl
locals {
foo = uuid()
bar = local.foo
}
local.foo # => 550e8400-e29b-41d4-a716-446655440000
local.bar # => 89e2e3fd-32a3-1412-085a-8b7c78353750
local.foo # => …
```
> terraform: Cache resolved local values

- docs/user-guide/annotations.md
Clarifies that annotations are for ignoring issues from rules, not errors parsing HCL documents or evaluating their expressions. A search for `tflint-ignore error` turns up plenty of existing issues, among them:
https://github.com/terraform-linters/tflint/discussions/2310
https://github.com/terraform-linters/tflint/issues/1688
https://github.com/terraform-linters/tflint/issues/1353
> docs: annotations cannot ignore errors

- cmd/cli.go
- cmd/inspect.go
- cmd/inspect_parallel.go
- integrationtest/cli/chdir_format/subdir/.tflint.hcl
- integrationtest/cli/cli_test.go
- integrationtest/cli/format_config/.tflint.hcl
Fixes https://github.com/terraform-linters/tflint/issues/2305
Due to a regression introduced by the [parallel inspection added in v0.51](https://github.com/terraform-linters/tflint/pull/2021), the `format` that can be set in the config file was always ignored.
This PR changes the `inspectModule` so that the `format` setting is set to the `cli.formatter.Format` after loading the config file. Note that this is intentionally not set with `--recursive`, as mentioned in the documentation.
> cmd: Apply `format` set in config file

- docs/user-guide/compatibility.md
- go.mod
- go.sum
This PR adds support for Terraform v1.12.
The only changes that actually affect you are HCL updates. See also https://github.com/hashicorp/terraform/pull/36224
> Add support for Terraform v1.12

- .github/ISSUE_TEMPLATE/bug.yml
- .github/workflows/issues.yml
Call out to https://github.com/terraform-linters/actions-workflows/blob/main/.github/workflows/validate-terraform-issues.yml to validate any submitted issue with a triple backtick `terraform` code block. If `terraform init && terraform validate` don't pass, warn the user that they must fix their config.
Goal: discourage users from frequent submissions of broken configuration with elided sections, references to other files, etc. Emphasize that they are expected to provide something we can copy and paste. Avoid time-waster issues caused by users running outdated Terraform versions.
> workflow: validate issues

- install_linux.sh
The GitHub API throws rate errors when you don't pass a GitHub token. By using the "latest" release forward link you don't need to query the version at all
Related to https://github.com/terraform-linters/tflint/issues/1988
Related to https://github.com/terraform-linters/tflint/issues/2175
> fix(script): GitHub API rate limit
